### ISSUE TITLE
Can't import .nif file

### ISSUE THREAD

**Issue by ZukiLTU** [niftools/blender_niftools_addon#392]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
I'm trying to import a .nif file, but with every .nif file it returns that message : 
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_nif\dependencies\pyffi\formats\nif\__init__.py", line 1375, in read
    block = getattr(NifFormat, block_type)()
AttributeError: type object 'NifFormat' has no attribute 'NiPhysXScene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 125, in execute
    return nif_import.NifImport(self, context).execute()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\nif_import.py", line 73, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data.read(nif_stream)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_nif\dependencies\pyffi\formats\nif\__init__.py", line 1378, in read
    "Unknown block type '%s'." % block_type)
ValueError: Unknown block type 'NiPhysXScene'.

location: <unknown location>:-1

```
### Blender Niftools Addon Version Info
2.6.0.dev4

### Blender Version Info
2.8.1

### Platform information
Windows 10

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
1- Import a .nif file
2- Get an error message.

## Expected Result
I wanted to Blender to open the file.

## Actual Result
I'm getting this message : 
```
bpy.context.space_data.system_bookmarks_active = 1
Dev: Sys variable not set
Executing - Niftools : Blender Niftools Addon v0.0.2(running on Blender 2.81 (sub 16), PyFFI 2.2.4.dev4)
Importing C:\Users\User\Desktop\todo\natere_tree3001_01.nif
NIF file version: 14020008
Reading file
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_nif\dependencies\pyffi\formats\nif\__init__.py", line 1375, in read
    block = getattr(NifFormat, block_type)()
AttributeError: type object 'NifFormat' has no attribute 'NiPhysXScene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 125, in execute
    return nif_import.NifImport(self, context).execute()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\nif_import.py", line 73, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data.read(nif_stream)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_scene_nif\dependencies\pyffi\formats\nif\__init__.py", line 1378, in read
    "Unknown block type '%s'." % block_type)
ValueError: Unknown block type 'NiPhysXScene'.

location: <unknown location>:-1
```
## Screenshot
[Screenshot](https://prnt.sc/vq2evf)

### Nif File
[Nif file](https://www.mediafire.com/file/8vkwcjucl8nb8dg/natere_tree3001_01.nif/file)
## Additional Information
I'm using : 
- Python 3.9

**Comment by neomonkeus** [comment]
Not sure how you were able to assign labels. Need to look into that.

**Comment by neomonkeus** [comment]
The issue is that NiPhysXScene blocks are not not supported by the addon.

**Comment by SubhadeepG** [comment]
The unknown block NiPhysXScene is not present inside the nif xml and even NifSkope could not open it. What game is this nif from?

**Comment by ZukiLTU** [comment]
> The unknown block NiPhysXScene is not present inside the nif xml and even NifSkope could not open it. What game is this nif from?

It's from Dragonica, idk if you know this game.
