### ISSUE TITLE
cant import export catherine classic .nif files

### ISSUE THREAD

**Issue by kroamele1232** [niftools/blender_niftools_addon#421]
@niftools/blender-niftools-addon-reviewer -

# Issue Overview

i cant import catherine classic .nif files

### Blender Niftools Addon Version Info

i use 0.0.3 and 0.0.4 always give error

### Blender Version Info

blender 2.8,2.83,2.91 

### Platform information
Windows 10 pro 64 bit

## Context

i try catherine classic nif file to import blender always give  error i try everything cant import 

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #.  

im download nif blender plugin and launch blender add addons and try import catherine classic .nif file not work 

## Expected Result
**[Describe what you expected to have resulted from this process]**

i want export and import i need translate menus 

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**

give error log 

## Screenshot
**[If relevant, include a screenshot]**

![image](https://user-images.githubusercontent.com/74860011/112405038-8f72c500-8d22-11eb-898b-36bd13ffe9b8.png)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

Python: Traceback (most recent call last):
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 70, in __init__
    NifCommon.__init__(self, operator, context)
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_common.py", line 63, in __init__
    from . import bl_info
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\__init__.py", line 117, in <module>
    operators.register()
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\__init__.py", line 66, in register
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\utils\decorators.py", line 93, in register_modules
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\object.py", line 105, in register
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\utils\decorators.py", line 79, in register_classes
ValueError: register_class(...): already registered as a subclass 'BSXExtraDataAdd'

location: <unknown location>:-1

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**

location: <unknown location>:-1
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Loading: Blender Niftools Addon: v0.0.3
niftools:INFO:Loading: Blender Niftools Addon: v0.0.3
niftools:INFO:Loading: Blender Niftools Addon: v0.0.3
niftools:INFO:Loading: Blender Niftools Addon: v0.0.3
niftools:INFO:Loading: Pyffi: 2.2.4.dev3
niftools:INFO:Loading: Pyffi: 2.2.4.dev3
niftools:INFO:Loading: Pyffi: 2.2.4.dev3
niftools:INFO:Loading: Pyffi: 2.2.4.dev3
Python: Traceback (most recent call last):
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 70, in __init__
    NifCommon.__init__(self, operator, context)
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_common.py", line 63, in __init__
    from . import bl_info
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\__init__.py", line 117, in <module>
    operators.register()
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\__init__.py", line 66, in register
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\utils\decorators.py", line 93, in register_modules
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\object.py", line 105, in register
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\utils\decorators.py", line 79, in register_classes
ValueError: register_class(...): already registered as a subclass 'BSXExtraDataAdd'

location: <unknown location>:-1

**Comment by neomonkeus** [comment]
Can you provide the files you were trying to import, or is the menu not showing up at all?

**Comment by kroamele1232** [comment]
he's just give error. Nothing else is happening. 

https://www24.zippyshare.com/v/p0K89MxT/file.html

**Comment by neomonkeus** [comment]
Is the import/export menu available?

**Comment by kroamele1232** [comment]
yes

**Comment by neomonkeus** [comment]
Can you upgrade to v0.0.4. 
This image shows how to use the inbuilt updater - https://user-images.githubusercontent.com/525919/99152545-518dd200-269a-11eb-9236-38c72e641884.gif

**Comment by kroamele1232** [comment]
okay 
![image](https://user-images.githubusercontent.com/74860011/112469303-61b96a80-8d7a-11eb-8489-d0f548b56edd.png)

![image](https://user-images.githubusercontent.com/74860011/112469354-70a01d00-8d7a-11eb-93fd-9456785dae19.png)

**Comment by kroamele1232** [comment]
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.4(running on Blender 2.91.2, PyFFI 2.2.4.dev3)
niftools:INFO:Importing C:\Users\Uyg\Downloads\Catherine.Classic.Build.4051080\Catherine.Classic.Build.4051080\data\title\A_attach_font_ni.nif
niftools:INFO:NIF file version: 14060000
niftools:INFO:Reading file
niftools:INFO:Importing data
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 0.100000
pyffi.toaster:INFO:  ~~~ NiNode [´┐¢V´┐¢[´┐¢´┐¢ ´┐¢´┐¢´┐¢[´┐¢g] ~~~
pyffi.toaster:INFO:    ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:    ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiZBufferProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [] ~~~
pyffi.toaster:INFO:      ~~~ NiNode [A_attach_menu_root01] ~~~
pyffi.toaster:INFO:        ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiNode [A_attach_menu_root01 NonAccum] ~~~
pyffi.toaster:INFO:          ~~~ NiNode [menu_font_a_root] ~~~
pyffi.toaster:INFO:            ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:            ~~~ NiMesh [menu_01] ~~~
pyffi.toaster:INFO:              ~~~ NiBooleanExtraData [dxStdMat] ~~~
pyffi.toaster:INFO:              ~~~ NiIntegerExtraData [effect] ~~~
pyffi.toaster:INFO:              ~~~ NiBooleanExtraData [enabled] ~~~
pyffi.toaster:INFO:              ~~~ NiMaterialProperty [b] ~~~
pyffi.toaster:INFO:                ~~~ NiMaterialColorController [] ~~~
pyffi.toaster:INFO:              ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:              ~~~ NiAlphaProperty [] ~~~
pyffi.toaster:INFO:              ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:                ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:                  ~~~ NiPixelData [] ~~~
pyffi.toaster:INFO:              ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:              ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [menu_00] ~~~
pyffi.toaster:INFO:              ~~~ NiMesh [´┐¢ÊÅW´┐¢┬ö\´┐¢´┐¢´┐¢b´┐¢V´┐¢´┐¢] ~~~
pyffi.toaster:INFO:                ~~~ NiBooleanExtraData [dxStdMat] ~~~
pyffi.toaster:INFO:                ~~~ NiIntegerExtraData [effect] ~~~
pyffi.toaster:INFO:                ~~~ NiBooleanExtraData [enabled] ~~~
pyffi.toaster:INFO:                ~~~ NiMaterialProperty [a] ~~~
pyffi.toaster:INFO:                  ~~~ NiMaterialColorController [] ~~~
pyffi.toaster:INFO:                ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:                ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:            ~~~ NiMesh [menu_03] ~~~
pyffi.toaster:INFO:              ~~~ NiBooleanExtraData [dxStdMat] ~~~
pyffi.toaster:INFO:              ~~~ NiIntegerExtraData [effect] ~~~
pyffi.toaster:INFO:              ~~~ NiBooleanExtraData [enabled] ~~~
pyffi.toaster:INFO:              ~~~ NiMaterialProperty [d] ~~~
pyffi.toaster:INFO:                ~~~ NiMaterialColorController [] ~~~
pyffi.toaster:INFO:              ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:              ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [menu_02] ~~~
pyffi.toaster:INFO:              ~~~ NiMesh [´┐¢ÊÅW´┐¢┬ö\´┐¢´┐¢´┐¢b´┐¢V´┐¢´┐¢@#0] ~~~
pyffi.toaster:INFO:                ~~~ NiBooleanExtraData [dxStdMat] ~~~
pyffi.toaster:INFO:                ~~~ NiIntegerExtraData [effect] ~~~
pyffi.toaster:INFO:                ~~~ NiBooleanExtraData [enabled] ~~~
pyffi.toaster:INFO:                ~~~ NiMaterialProperty [c] ~~~
pyffi.toaster:INFO:                  ~~~ NiMaterialColorController [] ~~~
pyffi.toaster:INFO:                ~~~ NiDataStream [] ~~~
pyffi.toaster:INFO:                ~~~ NiDataStream [] ~~~
Python: Traceback (most recent call last):
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 135, in execute
    self.import_root(root)
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 173, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\Uyg\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 217, in import_branch
    NifLog.info(f"Importing data for block '{n_block.name.decode()}'")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte

location: <unknown location>:-1

**Comment by neomonkeus** [comment]
Ok that looks a bit better.
It looks like this has a NiMesh block we we currently don't support reading of.
That is why you getting all the funky characters here ` pyffi.toaster:INFO: ~~~ NiMesh [´┐¢ÊÅW´┐¢┬ö\´┐¢´┐¢´┐¢b´┐¢V´┐¢´┐¢@#0] ~~~`

And it it ultimately failing here `NifLog.info(f"Importing data for block '{n_block.name.decode()}'")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte`
because it can't "understand" the data

**Comment by kroamele1232** [comment]
is there any chance you can fix this?

**Comment by neomonkeus** [comment]
This isn't so much a fix as it requires new functionality altogether to be implemented.

It depends what your goal is.
I could look at this and see if I give you a quick fix to bypass the failure point so import completes, but it won't have any mesh data.
If you want full support, probably not going to be any time soon.

**Comment by kroamele1232** [comment]
i just wanted to import and export maybe bypass could fix it.

**Comment by Shasties** [comment]
Built off of #442 but still having issues, hoping someone will have some insight. I was able to get the import to run to completion without throwing exceptions after adding in some more safe_decode calls. However, it looks like only the skeleton gets loaded (see below, this is in blender)
![image](https://user-images.githubusercontent.com/28744793/131581545-fd1a3195-244b-4d1b-8ce0-49344b5c165c.png)
Using nifskope, I was able to load up more of the .nif, but it's still incomplete. I can at least see that the blender plugin looks like the right shape (character above, various item assets below it).
![image](https://user-images.githubusercontent.com/28744793/131581872-c5316026-766b-4c95-8049-0168cf09e3c9.png)
Not sure where to go to further debug this atm. No error messages or anything I thought would be useful in the logs, but I can dump those if it'd be helpful.

**Comment by Candoran2** [comment]
It seems the nif file is no longer available because the file host shut down. Could you post it again? It should be able to put on the issue directly as a .zip file.

**Comment by Shasties** [comment]
I am not all that familiar with blender so this may be user error, but it seems like while the models now load, the textures don't seem to carry over. 
![image](https://github.com/niftools/blender_niftools_addon/assets/28744793/92773c07-97f4-41a7-9334-4b6f5f9272f0)

Here are a couple different models of player characters and bosses to help troubleshooting.
[41.zip](https://github.com/niftools/blender_niftools_addon/files/11827950/41.zip)
[22.zip](https://github.com/niftools/blender_niftools_addon/files/11827956/22.zip)
[01.zip](https://github.com/niftools/blender_niftools_addon/files/11827964/01.zip)

Additionally, simply trying to import and immediately export as nif gives an error:
Python: Traceback (most recent call last):
  File "...\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "...\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\nif_export.py", line 131, in execute
    self.version, data = scene.get_version_data()
  File "...\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\modules\nif_export\scene\__init__.py", line 53, in get_version_data
    user_version = b_scene.user_version if b_scene.user_version else b_scene.USER_VERSION.get(game, 0)
AttributeError: 'Scene' object has no attribute 'USER_VERSION'

**Comment by Candoran2** [comment]
If you want to use the textures that are embedded in the nif file, don't forget to tick 'Use Embedded Texture' on the import menu.

As for the export error, that should be fixed by this commit: https://github.com/Candoran2/blender_nif_plugin/commit/c8488a1c2326bb3f61d86da14eb2263dd902cfe7

**Comment by kroamele1232** [comment]
thank you

Candoran2 ***@***.***>, 22 Tem 2023 Cmt, 00:42 tarihinde şunu
yazdı:

**Comment by Shasties** [comment]
> Thanks for the models.
> 
> If you want to use the textures that are embedded in the nif file, don't forget to tick 'Use Embedded Texture' on the import menu.
> 
> As for the export error, that should be fixed by this commit: [Candoran2@c8488a1](https://github.com/Candoran2/blender_nif_plugin/commit/c8488a1c2326bb3f61d86da14eb2263dd902cfe7)

Importing with embedded texture made no difference

**Comment by Candoran2** [comment]
> Importing with embedded texture made no difference
And you're certain that you're in 'Material Preview' or 'Rendered' mode for the viewport shading, rather than the 'solid' option you've selected in your screenshot?
