### ISSUE TITLE
bones/model not same position

### ISSUE THREAD

**Issue by Terankuro** [niftools/blender_niftools_addon#448]
Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
Imported a nif file and the Body is not at the same position as the rig/bones

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
blender_niftools_addon-v0.0.6-2021-04-24-fa4123d
### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
Blender2.93/2.92 and 2.91(tried in all 3 Versions,but using 2.93)
### Platform information
**[Provide a brief overview of what OS your running on]**
Windows 10
## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
the import works fine but the bones with the animations are not connected to the body. Same problem when i import a kf(pur animation) file. 
## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 
open Blender,go to file-->import-->gamebryo(.nif)
## Expected Result
**[Describe what you expected to have resulted from this process]**
The bones should be in the body(the bones have a similar form as the body)
## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
The body(model) lies on the ground under the bones and is not connected at all(and doesnt move if animations are involved)
## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**
i dont know. i installed Blender 2.49b/python2.6/pyffi/nifscripts 2.5.5  and there the bones/body is imported correctly 
## Screenshot
**[If relevant, include a screenshot]**
https://ibb.co/vXqqZPL

https://ibb.co/wsmHVNM
## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**
bpy.ops.object.delete(use_global=False)
Deleted 1 object(s)
bpy.context.space_data.system_bookmarks_active = 1
bpy.context.space_data.system_bookmarks_active = 5
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
Dev: Sys variable not set
Executing - Niftools : Blender Niftools Addon v0.0.6(running on Blender 2.91.0, PyFFI 2.2.4.dev3)
Importing C:\Users\armin\OneDrive\Bilder\D1_01_007a_Base.nif
NIF file version: 14010003
Reading file
Importing data
Scale Correction set to 0.10000000149011612
Importing data for block 'Scene Root'
Importing data for block 'D1_01_007a'
Importing data for block 'boom_top'
Importing data for block 'body'
Importing data for block 'Editable Mesh'
Importing mesh data for geometry 'Editable Mesh'
Python: Traceback (most recent call last):
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 132, in execute
    self.import_root(root)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 170, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  [Previous line repeated 1 more time]
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 216, in import_branch
    return self.objecthelper.import_geometry_object(b_armature, n_block)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\object\__init__.py", line 142, in import_geometry_object
    self.mesh.import_mesh(n_block, b_obj)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\geometry\mesh\__init__.py", line 94, in import_mesh
    self.mesh_prop_processor.process_property_list(n_block, b_obj)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\geometry\mesh.py", line 113, in process_property_list
    self.process_property(prop)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\geometry\niproperty.py", line 134, in process_nitexturing_property
    NiTextureProp().import_nitextureprop_textures(prop, self._nodes_wrapper)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\types\nitextureprop.py", line 65, in import_nitextureprop_textures
    nodes_wrapper.create_and_link(slot_name, n_tex)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\nodes_wrapper\__init__.py", line 262, in create_and_link
    b_texture = self.create_texture_slot(n_tex_info)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\nodes_wrapper\__init__.py", line 269, in create_texture_slot
    b_image = self.texture_loader.import_texture_source(n_tex_desc.source)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\loader.py", line 77, in import_texture_source
    if isinstance(source, NifFormat.NiSourceTexture) and not source.use_external and texture.IMPORT_EMBEDDED_TEXTURES:
AttributeError: module 'io_scene_niftools.modules.nif_import.property.texture' has no attribute 'IMPORT_EMBEDDED_TEXTURES'

location: <unknown location>:-1

[Neuer Ordner.zip](https://github.com/niftools/blender_niftools_addon/files/6739704/Neuer.Ordner.zip)

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**
Python: Traceback (most recent call last):
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 132, in execute
    self.import_root(root)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 170, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 251, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature, n_armature=n_armature)
  [Previous line repeated 1 more time]
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 216, in import_branch
    return self.objecthelper.import_geometry_object(b_armature, n_block)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\object\__init__.py", line 142, in import_geometry_object
    self.mesh.import_mesh(n_block, b_obj)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\geometry\mesh\__init__.py", line 94, in import_mesh
    self.mesh_prop_processor.process_property_list(n_block, b_obj)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\geometry\mesh.py", line 113, in process_property_list
    self.process_property(prop)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\python\lib\functools.py", line 840, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\geometry\niproperty.py", line 134, in process_nitexturing_property
    NiTextureProp().import_nitextureprop_textures(prop, self._nodes_wrapper)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\types\nitextureprop.py", line 65, in import_nitextureprop_textures
    nodes_wrapper.create_and_link(slot_name, n_tex)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\nodes_wrapper\__init__.py", line 262, in create_and_link
    b_texture = self.create_texture_slot(n_tex_info)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\nodes_wrapper\__init__.py", line 269, in create_texture_slot
    b_image = self.texture_loader.import_texture_source(n_tex_desc.source)
  File "C:\Users\armin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\modules\nif_import\property\texture\loader.py", line 77, in import_texture_source
    if isinstance(source, NifFormat.NiSourceTexture) and not source.use_external and texture.IMPORT_EMBEDDED_TEXTURES:
AttributeError: module 'io_scene_niftools.modules.nif_import.property.texture' has no attribute 'IMPORT_EMBEDDED_TEXTURES'

location: <unknown location>:-1

bpy.context.area.ui_type = 'INFO'

**Comment by neomonkeus** [comment]
I think this is fixed by #442 
I just need to find time to put out a release for the current code base and merge the two outstanding PRs.

**Comment by Terankuro** [comment]
Hello neomonkeus,
thank you for your quick response! If it is possible fixed by the next releases I´ll be happy to wait until then. So for now I´ll close this Thread
