### ISSUE TITLE
Animation Import Fails

### ISSUE THREAD

**Issue by josephbburg** [niftools/blender_niftools_addon#464]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [X] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Importing animation fails because of a NameError ("animation is not defined")
This seems to happen whenever I try to import animation for the current master branch, I'm using Morrowind's .nif models that I unfortunately can't share here.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
Current Master

### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
Blender 2.93.5

### Platform information
**[Provide a brief overview of what OS your running on]**
Manjaro GNU/Linux

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
I believe this was caused by 070c0be . When I checkout the parent commit, animation import works fine. When I checkout this commit, it gives me the error.

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 
Try to import animation from a .NIF file

## Expected Result
**[Describe what you expected to have resulted from this process]**
Geometry with animation should import

## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
A long error message, caused by a reference to a variable that isn't defined anymore in https://github.com/niftools/blender_niftools_addon/blob/master/io_scene_niftools/modules/nif_import/animation/__init__.py

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**
I believe this was caused by 070c0be .
I haven't read the commit carefully, but It seems it moves some stuff, but forgot to change the usage of the stuff that was moved. Maybe the old import statement could be added back? Or whatever was moved could be referenced instead of the old name?

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**
```
Python: Traceback (most recent call last):
  File "/home/theangerspecialist/.config/blender/2.93/scripts/addons/io_scene_niftools/operators/nif_import_op.py", line 122, in execute
    return NifImport(self, context).execute()
  File "/home/theangerspecialist/.config/blender/2.93/scripts/addons/io_scene_niftools/nif_import.py", line 98, in execute
    Animation.set_frames_per_second(NifData.data.roots)
  File "/home/theangerspecialist/.config/blender/2.93/scripts/addons/io_scene_niftools/modules/nif_import/animation/__init__.py", line 199, in set_frames_per_second
    fps = animation.FPS
NameError: name 'animation' is not defined
```

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**
(same as above)

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**
thanks for the addon, and bless you for updating it to modern Blenders.

**Comment by neomonkeus** [comment]
Missing information 
`[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]`

Console Output
`Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console`

**Comment by HENDRIX-ZT2** [comment]
This is one I fixed, should be fine in current release / master.

**Comment by josephbburg** [comment]
> This is one I fixed, should be fine in current release / master.

Thanks. Do you need more info? Or was that other reply just a bot?

**Comment by neomonkeus** [comment]
No, not a bot, as you haven't supplied the required details we can only assume you are on an old version. 
Can you retry with the latest release version either by manually installing or via the updater.
As you haven't supplied any files, we don't have anything further we can do as we are not able to reproduce.

**Comment by josephbburg** [comment]
I didn't share a .nif because I don't have any that aren't game files... I suppose I could make one for you if you want. I assume this will happen for any animation since it looks like a simple syntax error. I was using the master branch of the git repo, after the issue appeared when I updated it from within Blender. Then I did a bisect and I found the specific commit responsible. I don't think I can get any more specific than "here is the exact commit that created the issue".
If you want, I can make a .nif file or search online for something in a freely copyable mod or something. The issue affected every file I tried, though, so I imagine any file would work.
