### ISSUE TITLE
Addon v0.0.13 not working 

### ISSUE THREAD

**Issue by RaulMZE** [niftools/blender_niftools_addon#504]
Plugin installed on Blender as per instructed, installation process followed and yet error message occurs when trying to import a NIF file to Blender. Message error:

Python: Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1375, in read
    block = getattr(NifFormat, block_type)()
AttributeError: type object 'NifFormat' has no attribute 'BSTriShape'. Did you mean: 'NiTriShape'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 127, in execute
    return NifImport(self, context).execute()
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 75, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 141, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\file_io\nif.py", line 64, in load_nif
    data.read(nif_stream)
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1377, in read
    raise ValueError(
ValueError: Unknown block type 'BSTriShape'.

location: <unknown location>:-1

**Comment by neomonkeus** [comment]
@RaulMZE Because you removed the issue template, there is lots of required information missing.
Looking at the output ` ValueError: Unknown block type 'BSTriShape'.`. 
I can only surmise that that you are importing f04 which is not supported.

**Comment by RaulMZE** [comment]
I don't know much about these things so I didn't mess with it, just downloaded the rar and followed the process to make Blender read NIF files. I did not removed any issue template.

**Comment by RaulMZE** [comment]
@neomonkeus Is there any other required files I need to get before this? I just want Blender to be able to import/export file to NIF

**Comment by neomonkeus** [comment]
> I don't know much about these things so I didn't mess with it, just downloaded the rar and followed the process to make Blender read NIF files. I did not removed any issue template.

I have readded the template that is generated when a issue is created.

**Comment by neomonkeus** [comment]
> @neomonkeus Is there any other required files I need to get before this? I just want Blender to be able to import/export file to NIF

This comment already answers that question.
> Looking at the output ValueError: Unknown block type 'BSTriShape'..
> I can only surmise that that you are importing f04 which is not supported - https://github.com/niftools/blender_niftools_addon/discussions/473
