### ISSUE TITLE
ImportError: No module named common

### ISSUE THREAD

**Issue by Wuzy2121** [niftools/blender_niftools_addon#528]
@niftools/blender-niftools-addon-reviewer -

# Issue Overview
when trying to import a nif file, this is written in the console:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\import\import_nif.py", line 20, in <module>
    from nif_common import NifImportExport
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\bpymodules\nif_common.py", line 91, in <module>
    from pyffi.formats.nif import NifFormat
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\bpymodules\pyffi\formats\nif\__init__.py", line 348, in <module>
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\bpymodules\pyffi\formats\bsa\__init__.py", line 104, in <module>
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\bpymodules\pyffi\object_models\xml\__init__.py", line 50, in <module>
  File "C:\Program Files (x86)\Blender Foundation\Blender\.blender\scripts\bpymodules\pyffi\object_models\xml\struct_.py", line 48, in <module>
ImportError: No module named common

### Blender Niftools Addon Version Info
Blender Nifscripts v2.5.9

### Blender Version Info
2.49b

## Screenshot
https://imgur.com/a/kHX8BuP

**Comment by neomonkeus** [comment]
The `Blender Nifscripts v2.5.9` are no longer supported, please use a more modern version of the scripts.
