### ISSUE TITLE
Cannot export NIF

### ISSUE THREAD

**Issue by Fancy2209** [niftools/blender_niftools_addon#538]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [?] Read through the list of `Helpful resources` links on the right-hand side.
 - [?] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [X] Looking for support where the forums, chat or documentation is more appropriate.
 - [X] Goes off topic, loses focus or turns into a discussion.
 - [X] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**
When I try to export my model to NIF on Blender 3.3.1, it errors out.

### Blender Niftools Addon Version Info
**[Provide version information for the Blender Niftools Addon the issue occurs with, available in Blender in the Add-On section]**
v0.0.14
### Blender Version Info
**[Provide information on which version of Blender the issue is seen]**
3.3.1
### Platform information
**[Provide a brief overview of what OS your running on]**
Windows 10 21H2
## Context
**[Provide more detailed information to the issue itself and why it is relevant]**
I was trying to export a model to use it as a Custom Armor in FNV and FO3, but I cannot export the model to a NIF to continue
## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. Export a model as a NIF

## Expected Result
**[Describe what you expected to have resulted from this process]**
Get a NIF file of the model
## Actual Result
**[Describe what you currently experience from this process, and thereby explain the bug]**
It fails to export

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**
![image](https://user-images.githubusercontent.com/64917206/201139323-53ad66ab-cac1-4872-aa55-18360ed60bc3.png)

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**
```
Python: Traceback (most recent call last):
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_export.py", line 136, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 114, in export_root_node
    self.export_node(b_obj, self.n_root)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 234, in export_children
    self.export_node(b_child, temp_parent)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 180, in export_node
    mesh = self.mesh_helper.export_tri_shapes(b_obj, n_parent, self.n_root, b_obj.name)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 169, in export_tri_shapes
    self.object_property.export_properties(b_obj, b_mat, trishape)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\property\object\__init__.py", line 79, in export_properties
    bsshader = self.bss_helper.export_bs_shader_property(b_mat)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\property\shader\__init__.py", line 70, in export_bs_shader_property
    return bsshader
UnboundLocalError: local variable 'bsshader' referenced before assignment
```

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**
```
{'INFO'}: Loading: Blender Niftools Addon: v0.0.14
{'INFO'}: Loading: PyFFi: 2.2.4.dev3
{'DEBUG'}: Starting registration
{'DEBUG'}: Configuring auto-updater
io_scene_niftools updater verbose is enabled
io_scene_niftools Updater: Read in JSON settings from file
{'DEBUG'}: Registering submodules for: io_scene_niftools
{'DEBUG'}: Registering Classes for module: io_scene_niftools.update
{'DEBUG'}: Registered Classes: ['UpdaterPreferences']
{'DEBUG'}: Registering submodules for: io_scene_niftools.properties
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.armature
{'DEBUG'}: Registered Classes: ['BoneProperty', 'ArmatureProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.collision
{'DEBUG'}: Registered Classes: ['CollisionProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.constraint
{'DEBUG'}: Registered Classes: ['ConstraintProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.material
{'DEBUG'}: Registered Classes: ['Material', 'AlphaFlags']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.object
{'DEBUG'}: Registered Classes: ['ExtraData', 'ExtraDataStore', 'ObjectProperty', 'BsInventoryMarker']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.shader
{'DEBUG'}: Registered Classes: ['ShaderProps']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.scene
{'DEBUG'}: Registered Classes: ['Scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.properties.armature', 'io_scene_niftools.properties.collision', 'io_scene_niftools.properties.constraint', 'io_scene_niftools.properties.material', 'io_scene_niftools.properties.object', 'io_scene_niftools.properties.shader', 'io_scene_niftools.properties.scene']
{'DEBUG'}: Registering submodules for: io_scene_niftools.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.object
{'DEBUG'}: Registered Classes: ['BSXExtraDataAdd', 'UPBExtraDataAdd', 'SampleExtraDataAdd', 'NiExtraDataRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.geometry
{'DEBUG'}: Registered Classes: ['BsInvMarkerAdd', 'BsInvMarkerRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_import_op
{'DEBUG'}: Registered Classes: ['NifImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_export_op
{'DEBUG'}: Registered Classes: ['NifExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_import_op
{'DEBUG'}: Registered Classes: ['KfImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_export_op
{'DEBUG'}: Registered Classes: ['KfExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.egm_import_op
{'DEBUG'}: Registered Classes: ['EgmImportOperator']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.operators.object', 'io_scene_niftools.operators.geometry', 'io_scene_niftools.operators.nif_import_op', 'io_scene_niftools.operators.nif_export_op', 'io_scene_niftools.operators.kf_import_op', 'io_scene_niftools.operators.kf_export_op', 'io_scene_niftools.operators.egm_import_op']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.armature
{'DEBUG'}: Registered Classes: ['BonePanel', 'ArmaturePanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.collision
{'DEBUG'}: Registered Classes: ['CollisionBoundsPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.material
{'DEBUG'}: Registered Classes: ['MaterialColorPanel', 'MaterialFlagPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.object
{'DEBUG'}: Registered Classes: ['ObjectBSInvMarkerPanel', 'ObjectExtraDataList', 'ObjectExtraDataType', 'ObjectExtraData', 'ObjectPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators
{'DEBUG'}: Registered Classes: ['OperatorCommonDevPanel']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_import
{'DEBUG'}: Registered Classes: ['OperatorImportIncludePanel', 'OperatorImportTransformPanel', 'OperatorImportGeometryPanel', 'OperatorImportTexturePanel', 'OperatorImportArmaturePanel', 'OperatorImportAnimationPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_export
{'DEBUG'}: Registered Classes: ['OperatorExportTransformPanel', 'OperatorExportArmaturePanel', 'OperatorExportAnimationPanel', 'OperatorExportOptimisePanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.operators.nif_import', 'io_scene_niftools.ui.operators.nif_export']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.shader
{'DEBUG'}: Registered Classes: ['ShaderPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.scene
{'DEBUG'}: Registered Classes: ['ScenePanel', 'SceneVersionInfoPanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.armature', 'io_scene_niftools.ui.collision', 'io_scene_niftools.ui.material', 'io_scene_niftools.ui.object', 'io_scene_niftools.ui.operators', 'io_scene_niftools.ui.shader', 'io_scene_niftools.ui.scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.update', 'io_scene_niftools.properties', 'io_scene_niftools.operators', 'io_scene_niftools.ui']
Read blend: C:\Users\conce\Downloads\untitled.blend
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.0.14(running on Blender 3.3.1, PyFFI 2.2.4.dev3)
niftools:INFO:Exporting C:\Users\conce\Downloads\untitled.nif
niftools:INFO:Exporting
niftools:INFO:Exporting geometry and animation
niftools:INFO:Writing NIF version 0x14020007
niftools:INFO:Created meta root because blender scene had multiple root objects
niftools:INFO:Exporting NiNode block
niftools:INFO:Exporting <bpy_struct, Object("HumanHead") at 0x0000028A158EF908> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("Bip01 Spine2") at 0x0000028A158FB908> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("Bip01 Clavicle.L") at 0x0000028A158FB748> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("Bip01 Neck1") at 0x0000028A158FB588> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("Bip01 Head") at 0x0000028A158FB3C8> as NiNode block
niftools:INFO:Exporting <bpy_struct, Bone("Bip01 Clavicle.R") at 0x0000028A158FB208> as NiNode block
niftools:INFO:Exporting BSBound block
niftools:INFO:Exporting <bpy_struct, Object("BSBound") at 0x0000028A00F78108> as bhkCollisionObject block
niftools:INFO:Exporting <bpy_struct, Object("BSBound") at 0x0000028A00F78108> as bhkRigidBody block
niftools:INFO:Exporting <bpy_struct, Object("BSBound") at 0x0000028A00F78108> as bhkConvexTransformShape block
niftools:INFO:Exporting <bpy_struct, Object("BSBound") at 0x0000028A00F78108> as bhkBoxShape block
niftools:INFO:Exporting <bpy_struct, Object("HeadMale") at 0x0000028A00F7B908>
niftools:INFO:Exporting <bpy_struct, Object("HeadMale") at 0x0000028A00F7B908> as NiTriShape block
niftools:INFO:Exporting NiSpecularProperty block
niftools:INFO:Exporting NiMaterialProperty block
Traceback (most recent call last):
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 140, in execute
    return NifExport(self, context).execute()
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_export.py", line 136, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 114, in export_root_node
    self.export_node(b_obj, self.n_root)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 218, in export_node
    self.export_children(b_obj, node)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 234, in export_children
    self.export_node(b_child, temp_parent)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 180, in export_node
    mesh = self.mesh_helper.export_tri_shapes(b_obj, n_parent, self.n_root, b_obj.name)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 169, in export_tri_shapes
    self.object_property.export_properties(b_obj, b_mat, trishape)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\property\object\__init__.py", line 79, in export_properties
    bsshader = self.bss_helper.export_bs_shader_property(b_mat)
  File "C:\Users\conce\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\modules\nif_export\property\shader\__init__.py", line 70, in export_bs_shader_property
    return bsshader
UnboundLocalError: local variable 'bsshader' referenced before assignment
```
### Blend File
**[Attach the blend file if the issue is reproducible]**
[blend.zip](https://github.com/niftools/blender_niftools_addon/files/9982444/blend.zip)

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
N/A

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**
Coudln't find them

## Additional Information
**[Anything else you feel is relevant]**
Nothing I could remeber at this time

**Comment by Candoran2** [comment]
I think I see why the error occurs - we don't have any code for exporting a BSShaderProperty, as opposed to the other shader types. Are meshes for the game you're trying to export for typically BSShaderProperty? For example, I think I've seen Fallout 3 models with a BSShaderPPLightingProperty.

**Comment by Fancy2209** [comment]
This was fallout 3 yes

**Comment by Candoran2** [comment]
> This was fallout 3 yes

Do you know if the nif files for that usually have a BSShaderProperty? Or do they actually use other shaders?
