### ISSUE TITLE
Blender recent version failed to import error with any Niftools version

### ISSUE THREAD

**Issue by AidenZapper** [niftools/blender_niftools_addon#542]
Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

### Blender Niftools Addon Version Info
**0.0.14**

### Blender Version Info
**3.1.2**

### Platform information
**Windows 10 x64 latest**

## Context
**Doesn't matter any plugin version. It sucks this addon won't work in a easy way to to import unless it's an alpha addon**

## Expected Result
*Just to work normally unlike other Blender plugin*

## Screenshot
**[If relevant, include a screenshot]**

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
![Screenshot 2022-11-21 094304](https://user-images.githubusercontent.com/110077984/203022660-6a5f2107-4088-4ef0-aa9d-f4110e6d0e3b.png)

**Comment by Candoran2** [comment]
Could you post the nif file you're trying to import, as well as the game it's from?

**Comment by AidenZapper** [comment]
It can be any nif file import I tried

**Comment by Candoran2** [comment]
> 

Even so, could you post at least one nif with which the error occurs for you?

**Comment by SumikoMei** [comment]
Here is a link to an example nif file that gives this same error. The file is used in the game Fallout 4.
As mentioned, it appears that any nif file from this game that I try to import results in the same "string too long" error.
[https://drive.google.com/file/d/1WrnKnIEB9mKUJm5bZb_2Tegv8M6TWU0P/view?usp=share_link](https://drive.google.com/file/d/1WrnKnIEB9mKUJm5bZb_2Tegv8M6TWU0P/view?usp=share_link)

Full error as reported by the console:

> `Executing - Niftools : Blender Niftools Addon v0.0.14(running on Blender 3.3.2, PyFFI 2.2.4.dev3)
Importing V:\F4 Mods\F4MO\mods\M1 Garand-20687-1-6-5\Meshes\Weapons\M1Garand\M1Garand_Barrel.nif
NIF file version: 14020007
Reading file
Python: Traceback (most recent call last):
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 127, in execute
    return NifImport(self, context).execute()
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_import.py", line 75, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\nif_import.py", line 141, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\file_io\nif.py", line 64, in load_nif
    data.read(nif_stream)
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1297, in read
    self.header.read(stream, data=self)
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\xml\struct_.py", line 373, in read
    attr_value.read(stream, data)
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\xml\array.py", line 303, in read
    elem.read(stream, data)
  File "C:\Users\sumis\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\common.py", line 667, in read
    raise ValueError('string too long (0x%08X at 0x%08X)'
ValueError: string too long (0x465F5C3A at 0x00000055)
`

**Comment by Candoran2** [comment]
@SumikoMei Fallout 4 isn't supported right now, see also #473 . If, however, there are nifs from games that *are* supported that error when trying to import them, please let us know. It's one of the reasons we ask for nifs - to see if it is one of the supported types.

**Comment by NidusUmbra** [comment]
> 

This [no Fallout 4 support] is mentioned nowhere. Perhaps you should? I appreciate your gargantuan effort in producing this addon but to also include one sentence in your description/README and/or website conveying this crucial information shouldn't be too much to ask.

**Comment by Candoran2** [comment]
I think this can be closed now. Fallout 4 import is relatively complete, at least geometry/armature wise. Export is still a to-do, but the errors here are (obviously) import-focused.
