### ISSUE TITLE
ValueError: chr() arg not in range(0x110000) when trying to import Oblivion .nif

### ISSUE THREAD

**Issue by Allofich** [niftools/blender_niftools_addon#548]
# Issue Overview
A .nif file that comes with Oblivion fails to import.

### Blender Niftools Addon Version Info
Built the addon using the following:
Python 3.11
New Pyffi: https://github.com/Candoran2/new-pyffi/commit/c8508fe316aa2e978e7677308f06f1b6a2ff48e4
New nif xml: https://github.com/niftools/nifxml/commit/89d03ffe69254ef4b3b58b0a22ec2ff9820b2e63
Latest blender addon code at: https://github.com/Candoran2/blender_nif_plugin/commit/c02a50b5c46e3d7e4088b3dd76f1181e348a6a9b

### Blender Version Info
3.4

### Platform information
Windows 11 22H2

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Build the latest blender_niftools_addon using the code versions listed above.
2. Import `meshes/architecture/anvil/lorgenhand01.nif` from Oblivion into Blender. This file can be obtained by extracting it from `data/Oblivion - Meshes.bsa` with a BSA extracting program.
3. The file fails to import with an error.
## Expected Result
Should import without errors.

## Actual Result
Fails to import.

### Console Output
```
Reading <class 'generated.formats.nif.nianimation.niobjects.NiBlendPoint3Interpolator.NiBlendPoint3Interpolator'> failed
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 291, in read_blocks
    block = block_class.from_stream(stream, self, 0, None)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 346, in from_stream
    instance = cls(context, arg, template, set_default=False)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBlendPoint3Interpolator.py", line 16, in __init__
    super().__init__(context, arg, template, set_default=False)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBlendInterpolator.py", line 33, in __init__
    self.high_priority = Char.from_value(-128)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\basic.py", line 176, in from_value
    return chr(value)
ValueError: chr() arg not in range(0x110000)
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 523, in from_stream
    instance.read_blocks(stream)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 291, in read_blocks
    block = block_class.from_stream(stream, self, 0, None)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 346, in from_stream
    instance = cls(context, arg, template, set_default=False)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBlendPoint3Interpolator.py", line 16, in __init__
    super().__init__(context, arg, template, set_default=False)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBlendInterpolator.py", line 33, in __init__
    self.high_priority = Char.from_value(-128)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\basic.py", line 176, in from_value
    return chr(value)
ValueError: chr() arg not in range(0x110000)
```
### Nif File
[lorgenhand01.zip](https://github.com/niftools/blender_niftools_addon/files/10255204/lorgenhand01.zip)

The same error happens with the .nif whether taken from the GOG/Steam version or the DVD version.

**Comment by Candoran2** [comment]
Interesting. It seems char is used as a signed byte, and I hadn't anticipated this (only in the NiBlendInterpolator, which is why it hadn't shown up until now). I think the fix for this would be to implement a proper signed byte type and use that instead in the NiBlendInterpolator, which would involve changes in both the xml and new-pyffi.

**Comment by Candoran2** [comment]
This specific error should be solved with the above two changes.

**Comment by Allofich** [comment]
I can confirm this error is fixed for every original Oblivion .nif I found that had the it (there were several).
