### ISSUE TITLE
marker_radius.nif from Oblivion fails with a long error message on import

### ISSUE THREAD

**Issue by Allofich** [niftools/blender_niftools_addon#549]
# Issue Overview
marker_radius.nif, a .nif file that comes with Oblivion, fails on import with a very long error message that has an exception and ends in garbage characters.

### Blender Niftools Addon Version Info
Built the addon using the following:
Python 3.11
New Pyffi: https://github.com/Candoran2/new-pyffi/commit/c8508fe316aa2e978e7677308f06f1b6a2ff48e4
New nif xml: https://github.com/niftools/nifxml/commit/89d03ffe69254ef4b3b58b0a22ec2ff9820b2e63
Latest blender addon code at: https://github.com/Candoran2/blender_nif_plugin/commit/c02a50b5c46e3d7e4088b3dd76f1181e348a6a9b

### Blender Version Info
3.4

### Platform information
Windows 11 22H2

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Build the latest blender_niftools_addon using the code versions listed above.
2. Import `meshes/marker_radius.nif` from Oblivion into Blender. This file can be obtained by extracting it from `data/Oblivion - Meshes.bsa` with a BSA extracting program.
3. The file fails to import with an error.
## Expected Result
Should import without errors (even if there is nothing to display).

## Actual Result
Errors.

### Console Output
```
niftools:INFO:NIF file version: 303000d
niftools:INFO:Reading .nif file
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 285, in read_blocks
    block_class = niobject_map[block_type]
KeyError: '\x00\x00\x00NiMaterialProperty\x00\x00\x00\x00ÿÿÿÿÿÿÿÿ\x01\x00\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x80?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80@\x00\x00\x80?\x0e\x00\x00\x00NiTriShapeData*\x00\x807\x8b\x00\x00\x00\x00\x00\x00\x00\x00\x00ÿÿ\x7f?P\x96\x06?\x00\x00\x00\x00?ÄY?Þ[&>\x00\x00\x00??ÄY?.ùd?\x00\x00\x00\x00-ùä>H-0?\x00\x00\x00?O\x96\x06?h\x83\x8d>@ÄY?-ùä>AÄÙ¾w7\x9e>?ÄY?R\x96\x86¾¼\x1bO?O\x96\x06?L>9¿N\x96\x06?-ùä>@ÄÙ¾z7\x9e¾?ÄY?@ÄY¿\x9a©Ö³O\x96\x06?K>9¿Q\x96\x06¿-ùä>å[&>ÿÿÿ¾?ÄY?M\x96\x86¾½\x1bO¿O\x96\x06?m\x83\x8d>?ÄY¿-ùä>I-0?þÿÿ¾O\x96\x06?qxs?s7\x9e¾\x00\x00\x00\x00pxs?x7\x9e>\x00\x00\x00\x00O>9?K\x96\x06¿-ùä¾AÄY?½\x1b\x0f4N\x96\x06¿L>9?O\x96\x06?-ùä¾\x18y\x16?¼\x1bO?\x00\x00\x00\x00 ¿8³\x00\x00\x80?\x00\x00\x00\x00P\x96\x86>¼\x1bO?O\x96\x06¿j\x83\x8d¾?ÄY?-ùä¾\x19y\x16¿¼\x1bO?\x00\x00\x00\x00qxs¿v7\x9e>\x00\x00\x00\x00I-0¿þÿÿ>O\x96\x06¿.ùd¿9ë§³-ùä¾pxs¿|7\x9e¾\x00\x00\x00\x00\x19y\x16¿½\x1bO¿\x00\x00\x00\x00H-0¿þÿÿ¾N\x96\x06¿l\x83\x8d¾?ÄY¿-ùä¾\x82OA2ÿÿ\x7f¿\x00\x00\x00\x00\x1cy\x16?¹\x1bO¿\x00\x00\x00\x00T\x96\x86>º\x1bO¿P\x96\x06¿\x00\x00\x00\x00\x00\x00\x00\x00ÿÿ\x7f¿â[&¾ÿÿÿ>?ÄY¿AÄÙ>x7\x9e>?ÄY¿P\x96\x06¿\x84fE³?ÄY¿ä[&¾ÿÿÿ¾?ÄY¿EÄÙ>t7\x9e¾?ÄY¿\x805\x8b\x00\x1c\x0fY2\x1c\x0fY±\x00\x00\x80?Q\x96\x06?c{51@ÄY?à[&>\x00\x00\x00?@ÄY?.ùd?TË"3.ùä>I-0?\x00\x00\x00?P\x96\x06?h\x83\x8d>@ÄY?/ùä>CÄÙ¾y7\x9e>@ÄY?T\x96\x86¾»\x1bO?R\x96\x06?M>9¿N\x96\x06?/ùä>@ÄÙ¾z7\x9e¾@ÄY?@ÄY¿§\x89y³Q\x96\x06?K>9¿P\x96\x06¿1ùä>ä[&>ÿÿÿ¾AÄY?M\x96\x86¾½\x1bO¿R\x96\x06?m\x83\x8d>@ÄY¿-ùä>I-0?þÿÿ¾Q\x96\x06?rxs?t7\x9e¾§\x89ù2qxs?z7\x9e>c{µ2N>9?N\x96\x06¿-ùä¾AÄY?¯p\x024O\x96\x06¿K>9?Q\x96\x06?-ùä¾\x1ay\x16?¼\x1bO?<Úb²w¥²²\x00\x00\x80?\x8c\x1c\x08³Q\x96\x86>½\x1bO?Q\x96\x06¿j\x83\x8d¾@ÄY?0ùä¾\x1by\x16¿»\x1bO?d{µ1qxs¿v7\x9e>c{52I-0¿ýÿÿ>Q\x96\x06¿.ùd¿\x86hí³.ùä¾pxs¿{7\x9e¾÷Ë\x1e³\x19y\x16¿½\x1bO¿Ñ*L³I-0¿ÿÿÿ¾Q\x96\x06¿i\x83\x8d¾@ÄY¿1ùä¾At\x134\x00\x00\x80¿°p\x82³\x1by\x16?»\x1bO¿;Úb³U\x96\x86>¼\x1bO¿Q\x96\x06¿\x00\x00\x00\x00N`ø1\x00\x00\x80¿â[&¾\x00\x00\x00?@ÄY¿AÄÙ>|7\x9e>@ÄY¿Q\x96\x06¿At\x93³@ÄY¿ã[&¾\x00\x00\x00¿@ÄY¿BÄÙ>v7\x9e¾AÄY¿\x00\x00\x00\x00\x00\x00\x003\x00\x00\x00\x00\x00\x00\x80?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00P\x00ð\x00\x00\x00\x00\x00\x01\x00\x02\x00\x01\x00\x03\x00\x04\x00\x01\x00\x04\x00\x02\x00\x02\x00\x04\x00\x05\x00\x00\x00\x02\x00\x06\x00\x02\x00\x05\x00\x07\x00\x02\x00\x07\x00\x06\x00\x06\x00\x07\x00\x08\x00\x00\x00\x06\x00\t\x00\x06\x00\x08\x00\n\x00\x06\x00\n\x00\t\x00\t\x00\n\x00\x0b\x00\x00\x00\t\x00\x0c\x00\t\x00\x0b\x00\r\x00\t\x00\r\x00\x0c\x00\x0c\x00\r\x00\x0e\x00\x00\x00\x0c\x00\x01\x00\x0c\x00\x0e\x00\x0f\x00\x0c\x00\x0f\x00\x01\x00\x01\x00\x0f\x00\x03\x00\x03\x00\x10\x00\x11\x00\x10\x00\x12\x00\x13\x00\x10\x00\x13\x00\x11\x00\x11\x00\x13\x00\x14\x00\x05\x00\x15\x00\x16\x00\x15\x00\x14\x00\x17\x00\x15\x00\x17\x00\x16\x00\x16\x00\x17\x00\x18\x00\x08\x00\x19\x00\x1a\x00\x19\x00\x18\x00\x1b\x00\x19\x00\x1b\x00\x1a\x00\x1a\x00\x1b\x00\x1c\x00\x0b\x00\x1d\x00\x1e\x00\x1d\x00\x1c\x00\x1f\x00\x1d\x00\x1f\x00\x1e\x00\x1e\x00\x1f\x00 \x00\x0e\x00!\x00"\x00!\x00 \x00#\x00!\x00#\x00"\x00"\x00#\x00\x12\x00\x14\x00\x15\x00\x11\x00\x15\x00\x05\x00\x04\x00\x15\x00\x04\x00\x11\x00\x11\x00\x04\x00\x03\x00\x18\x00\x19\x00\x16\x00\x19\x00\x08\x00\x07\x00\x19\x00\x07\x00\x16\x00\x16\x00\x07\x00\x05\x00\x1c\x00\x1d\x00\x1a\x00\x1d\x00\x0b\x00\n\x00\x1d\x00\n\x00\x1a\x00\x1a\x00\n\x00\x08\x00 \x00!\x00\x1e\x00!\x00\x0e\x00\r\x00!\x00\r\x00\x1e\x00\x1e\x00\r\x00\x0b\x00\x12\x00\x10\x00"\x00\x10\x00\x03\x00\x0f\x00\x10\x00\x0f\x00"\x00"\x00\x0f\x00\x0e\x00$\x00%\x00&\x00%\x00\x18\x00\x17\x00%\x00\x17\x00&\x00&\x00\x17\x00\x14\x00$\x00\'\x00%\x00\'\x00\x1c\x00\x1b\x00\'\x00\x1b\x00%\x00%\x00\x1b\x00\x18\x00$\x00(\x00\'\x00(\x00 \x00\x1f\x00(\x00\x1f\x00\'\x00\'\x00\x1f\x00\x1c\x00$\x00)\x00(\x00)\x00\x12\x00#\x00)\x00#\x00(\x00(\x00#\x00 \x00$\x00&\x00)\x00&\x00\x14\x00\x13\x00&\x00\x13\x00)\x00)\x00\x13\x00\x12\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 523, in from_stream
    instance.read_blocks(stream)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 287, in read_blocks
    raise ValueError(f"Unknown block type {block_type}.")
ValueError: Unknown block type NiMaterialPropertyÿÿÿÿÿÿÿÿ?????????@?NiTriShapeData*7ÿÿ?P??ÄY?Þ[&>??ÄY?.ùd?-ùä>H-0??O?h>@ÄY?-ùä>AÄÙ¾w7>?ÄY?R¾¼?O?L>9¿N?-ùä>@ÄÙ¾z7¾?ÄY?@ÄY¿©Ö³O?K>9¿Q¿-ùä>å[&>ÿÿÿ¾?ÄY?M¾½?O?m>?ÄY¿-ùä>I-0?þÿÿ¾O?qxs?s7¾pxs?x7>O>9?K¿-ùä¾AÄY?½N¿L>9?O?-ùä¾y?¼? ¿8³?P>¼?O¿j¾?ÄY?-ùä¾y¿¼?qxs¿v7>I-0¿þÿÿ>O¿.ùd¿9ë§³-ùä¾pxs¿|7¾y¿½?H-0¿þÿÿ¾N¿l¾?ÄY¿-ùä¾OA2ÿÿ¿y?¹?T>º?P¿ÿÿ¿â[&¾ÿÿÿ>?ÄY¿AÄÙ>x7>?ÄY¿P¿fE³?ÄY¿ä[&¾ÿÿÿ¾?ÄY¿EÄÙ>t7¾?ÄY¿5Y2Y±?Q?c{51@ÄY?à[&>?@ÄY?.ùd?TË"3.ùä>I-0??P?h>@ÄY?/ùä>CÄÙ¾y7>@ÄY?T¾»?R?M>9¿N?/ùä>@ÄÙ¾z7¾@ÄY?@ÄY¿§y³Q?K>9¿P¿1ùä>ä[&>ÿÿÿ¾AÄY?M¾½?R?m>@ÄY¿-ùä>I-0?þÿÿ¾Q?rxs?t7¾§ù2qxs?z7>c{µ2N>9?N¿-ùä¾AÄY?¯p4O¿K>9?Q?-ùä¾y?¼?<Úb²w¥²²?³Q>½?Q¿j¾@ÄY?0ùä¾¿»?d{µ1qxs¿v7>c{52I-0¿ýÿÿ>Q¿.ùd¿hí³.ùä¾pxs¿{7¾÷Ë³y¿½?Ñ*L³I-0¿ÿÿÿ¾Q¿i¾@ÄY¿1ùä¾At4¿°p³?»?;Úb³U>¼?Q¿N`ø1¿â[&¾?@ÄY¿AÄÙ>|7>@ÄY¿Q¿At³@ÄY¿ã[&¾¿@ÄY¿BÄÙ>v7¾AÄY¿3?Pð  

```
### Nif File
GOG/Steam version of the file
[marker_radius.zip](https://github.com/niftools/blender_niftools_addon/files/10258948/marker_radius.zip)

NifSkope can open this file without erroring (although it doesn't display anything in the render view). It can also be used in-game in Oblivion without crashing, although it just appears as a big yellow diamond with an exclamation point (the placeholder mesh).

**Comment by Candoran2** [comment]
This seems to be due to a misinterpretation of the comment text on the bool class on my part.

**Comment by Allofich** [comment]
Confirmed fixed by the above commit.
By the way, the game was auto-detected as "Munch's Oddysee". It's the first Oblivion mesh I've seen that was detected as that.
I don't know whether auto-detecting the wrong game is considered a problem or not (as you mentioned there is ambiguity), but if it is, this could be another .nif to consider for https://github.com/niftools/blender_niftools_addon/issues/546.

**Comment by Candoran2** [comment]
Detecting the wrong game *can* be an indication that the game is missing in the xml for that version, and ideally of course we'd add the game to all versions where it is used. However, that still wouldn't necessarily change which game is auto-detected (but ambiguous versions receive a warning).
