### ISSUE TITLE
Seemingly all Oblivion .kf files fail to import

### ISSUE THREAD

**Issue by Allofich** [niftools/blender_niftools_addon#553]
# Issue Overview
All .kf files that come with Oblivion that I have tried to import fail with `object has no attribute 'translation'. Did you mean: 'get_translations'?`

### Blender Niftools Addon Version Info
Built the addon using the following:
Python 3.11
New Pyffi: https://github.com/Candoran2/new-pyffi/commit/6d113fdcfcf950eae138f7e75efcc6b057c1d605
New nif xml: https://github.com/Candoran2/nifxml/commit/d0ab9271e2c2bf75eacb46082b93e1d304b551e6
Latest blender addon code at: https://github.com/Candoran2/blender_nif_plugin/commit/074489a44fcaf8657f969b3d10e7887b460b49be

### Blender Version Info
3.4

### Platform information
Windows 11 22H2

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
1. Build the latest blender_niftools_addon using the code versions listed above.
2. Import the problem .kf from Oblivion (below) into Blender.
3. The file fails to import with an error.
## Expected Result
Should import without errors.

## Actual Result
Fails to import with an error.

### Console Output
```
pyffi.toaster:INFO:    ~~~ NiBSplineCompTransformInterpolator [] ~~~
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\kf_import_op.py", line 67, in execute
    return KfImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\kf_import.py", line 74, in execute
    self.apply_scale(kfdata, NifOp.props.scale_correction)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\nif_common.py", line 77, in apply_scale
    SpellScale(data=data, toaster=toaster).recurse()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\pyffi\spells\__init__.py", line 290, in recurse
    self.recurse(child)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\pyffi\spells\__init__.py", line 304, in recurse
    self.recurse(child)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\pyffi\spells\__init__.py", line 299, in recurse
    if self.branchentry(branch):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\spells\nif\fix.py", line 509, in branchentry
    branch.apply_scale(self.toaster.scale)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBSplineCompTransformInterpolator.py", line 63, in apply_scale
    self.translation.x *= scale
AttributeError: 'NiBSplineCompTransformInterpolator' object has no attribute 'translation'. Did you mean: 'get_translations'?
```
### Nif File
[blockattack.zip](https://github.com/niftools/blender_niftools_addon/files/10298907/blockattack.zip)

**Comment by Allofich** [comment]
After updating to https://github.com/Candoran2/new-pyffi/commit/0dd9b2b37638e862695477089bcdac7e4ec17d2c, 
I can confirm that the error mentioned above no longer happens. I'm not sure how importing .kf files works, though, so I don't know whether importing is working or not.

When I import blockattack.kf, the following appears in the console:

```
niftools:INFO:NIF file version: 14000004
niftools:INFO:Reading .kf file
niftools:INFO:Scale Correction set to 0.10000000149011612
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 0.100000
pyffi.toaster:INFO:  ~~~ NiControllerSequence [BlockAttack] ~~~
pyffi.toaster:INFO:    ~~~ NiBSplineCompTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiBSplineData [] ~~~
pyffi.toaster:INFO:      ~~~ NiBSplineBasisData [] ~~~
pyffi.toaster:INFO:    ~~~ NiStringPalette [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiBSplineCompTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiBSplineCompTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:    ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:    ~~~ NiTextKeyExtraData [] ~~~
niftools:INFO:Animation estimated at 30 frames per second.
StringPalette: no string starts at offset 28 (string is b'Camera01', preceeding character is )
StringPalette: no string starts at offset 37 (string is b'Bip', preceeding character is )
StringPalette: no string starts at offset 41 (string is b'Bip01 Pelvis', preceeding character is )
StringPalette: no string starts at offset 54 (string is b'Bip01 Spine', preceeding character is )
StringPalette: no string starts at offset 66 (string is b'Bip01 Spine1', preceeding character is )
StringPalette: no string starts at offset 79 (string is b'Bip01 Spine2', preceeding character is )
StringPalette: no string starts at offset 92 (string is b'Bip01 Neck', preceeding character is )
StringPalette: no string starts at offset 103 (string is b'Bip01 Neck1', preceeding character is )
StringPalette: no string starts at offset 115 (string is b'Bip01 Head', preceeding character is )
StringPalette: no string starts at offset 126 (string is b'Bip01 L Clavicle', preceeding character is )
StringPalette: no string starts at offset 143 (string is b'Bip01 L UpperArm', preceeding character is )
StringPalette: no string starts at offset 160 (string is b'Bip01 L Forearm', preceeding character is )
StringPalette: no string starts at offset 176 (string is b'Bip01 L Hand', preceeding character is )
StringPalette: no string starts at offset 189 (string is b'Bip01 L Finger0', preceeding character is )
StringPalette: no string starts at offset 205 (string is b'Bip01 L Finger01', preceeding character is )
StringPalette: no string starts at offset 222 (string is b'Bip01 L Finger02', preceeding character is )
StringPalette: no string starts at offset 239 (string is b'Bip01 L Finger1', preceeding character is )
StringPalette: no string starts at offset 255 (string is b'Bip01 L Finger11', preceeding character is )
StringPalette: no string starts at offset 272 (string is b'Bip01 L Finger12', preceeding character is )
StringPalette: no string starts at offset 289 (string is b'Bip01 L Finger2', preceeding character is )
StringPalette: no string starts at offset 305 (string is b'Bip01 L Finger21', preceeding character is )
StringPalette: no string starts at offset 322 (string is b'Bip01 L Finger22', preceeding character is )
StringPalette: no string starts at offset 339 (string is b'Bip01 L Finger3', preceeding character is )
StringPalette: no string starts at offset 355 (string is b'Bip01 L Finger31', preceeding character is )
StringPalette: no string starts at offset 372 (string is b'Bip01 L Finger32', preceeding character is )
StringPalette: no string starts at offset 389 (string is b'Bip01 L Finger4', preceeding character is )
StringPalette: no string starts at offset 405 (string is b'Bip01 L Finger41', preceeding character is )
StringPalette: no string starts at offset 422 (string is b'Bip01 L Finger42', preceeding character is )
StringPalette: no string starts at offset 439 (string is b'Torch', preceeding character is )
StringPalette: no string starts at offset 445 (string is b'Bip01 L ForearmTwist', preceeding character is )
StringPalette: no string starts at offset 466 (string is b'Bip01 L UpperArmTwist', preceeding character is )
StringPalette: no string starts at offset 488 (string is b'Bip01 R Clavicle', preceeding character is )
StringPalette: no string starts at offset 505 (string is b'Bip01 R UpperArm', preceeding character is )
StringPalette: no string starts at offset 522 (string is b'Bip01 R Forearm', preceeding character is )
StringPalette: no string starts at offset 538 (string is b'Bip01 R Hand', preceeding character is )
StringPalette: no string starts at offset 551 (string is b'Bip01 R Finger0', preceeding character is )
StringPalette: no string starts at offset 567 (string is b'Bip01 R Finger01', preceeding character is )
StringPalette: no string starts at offset 584 (string is b'Bip01 R Finger02', preceeding character is )
StringPalette: no string starts at offset 601 (string is b'Bip01 R Finger1', preceeding character is )
StringPalette: no string starts at offset 617 (string is b'Bip01 R Finger11', preceeding character is )
StringPalette: no string starts at offset 634 (string is b'Bip01 R Finger12', preceeding character is )
StringPalette: no string starts at offset 651 (string is b'Bip01 R Finger2', preceeding character is )
StringPalette: no string starts at offset 667 (string is b'Bip01 R Finger21', preceeding character is )
StringPalette: no string starts at offset 684 (string is b'Bip01 R Finger22', preceeding character is )
StringPalette: no string starts at offset 701 (string is b'Bip01 R Finger3', preceeding character is )
StringPalette: no string starts at offset 717 (string is b'Bip01 R Finger31', preceeding character is )
StringPalette: no string starts at offset 734 (string is b'Bip01 R Finger32', preceeding character is )
StringPalette: no string starts at offset 751 (string is b'Bip01 R Finger4', preceeding character is )
StringPalette: no string starts at offset 767 (string is b'Bip01 R Finger41', preceeding character is )
StringPalette: no string starts at offset 784 (string is b'Bip01 R Finger42', preceeding character is )
StringPalette: no string starts at offset 801 (string is b'Weapon', preceeding character is )
StringPalette: no string starts at offset 808 (string is b'Bip01 R ForearmTwist', preceeding character is )
StringPalette: no string starts at offset 829 (string is b'Bip01 R UpperArmTwist', preceeding character is )
StringPalette: no string starts at offset 851 (string is b'BackWeapon', preceeding character is )
StringPalette: no string starts at offset 862 (string is b'Quiver', preceeding character is )
StringPalette: no string starts at offset 869 (string is b'Bip01 L Thigh', preceeding character is )
StringPalette: no string starts at offset 883 (string is b'Bip01 L Calf', preceeding character is )
StringPalette: no string starts at offset 896 (string is b'Bip01 L Foot', preceeding character is )
StringPalette: no string starts at offset 909 (string is b'Bip01 L Toe0', preceeding character is )
StringPalette: no string starts at offset 922 (string is b'Bip01 R Thigh', preceeding character is )
StringPalette: no string starts at offset 936 (string is b'Bip01 R Calf', preceeding character is )
StringPalette: no string starts at offset 949 (string is b'Bip01 R Foot', preceeding character is )
StringPalette: no string starts at offset 962 (string is b'Bip01 R Toe0', preceeding character is )
StringPalette: no string starts at offset 975 (string is b'SideWeapon', preceeding character is )
StringPalette: no string starts at offset 986 (string is b'Bip01 NonAccum', preceeding character is )
niftools:INFO:Finished successfully
```

The "no string starts at offset" lines look like warnings. Are they? The game after importing is `UNKNOWN` rather than `Oblivion KF` and I can't see anything imported, but I'm not quite sure what I should look for. I assume the .kf file needs to be combined with `skeleton.nif` in order to see any animations or the like, but even after importing `skeleton.nif` I didn't see any animation. (I'm still new to Blender and only know that you can pause/play an animation with the space key, but perhaps I need to select the animation somewhere?) Anyway, I'm thinking it still is probably not correctly importing the .kf file based on those "no string" lines.

**Comment by Candoran2** [comment]
They are warnings, yes. Seems I forgot to adjust one part of the StringPalette functions. It should be fixed in the commit I pushed just now (although there's still a theoretical mismatch that could occur with different string encoding formats, but that can be fixed in the future in a different way). Based on the code, the warnings themselves should have had no effect.
As for importing kfs, I haven't done much work with them. For the ones I tested (not this kf) you just had to import the nif file first, and then the kf file. Pressing space to play animations will then play the animation imported with the kf file.
The game does not get automatically set by importing kf files (unlike nif files), nor does it override nif or user versions.

**Comment by Allofich** [comment]
Alright, importing `skeleton.nif` and then a .kf file gives me different behavior.
In this case (still based on https://github.com/Candoran2/new-pyffi/commit/0dd9b2b37638e862695477089bcdac7e4ec17d2c), import of `blockattack.kf` fails with the following:

```
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\kf_import_op.py", line 67, in execute
    return KfImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\kf_import.py", line 79, in execute
    self.transform_anim.import_kf_root(kf_root, b_armature)
  File "****\Blender 3.4\3.4\python\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 209, in import_controller_sequence
    actions.add(self.import_keyframe_controller(kfc, b_armature_obj, b_target, b_action_name))
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 260, in import_keyframe_controller
    keys = list(n_kfc.get_translations())
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\nianimation\niobjects\NiBSplineCompTransformInterpolator.py", line 48, in get_translations
    self.translation_bias, self.translation_multiplier)
AttributeError: 'NiBSplineCompTransformInterpolator' object has no attribute 'translation_bias'. Did you mean: 'translation_offset'?
```

**Comment by Allofich** [comment]
Here's `skeleton.nif` for ease of testing.
[skeleton.zip](https://github.com/niftools/blender_niftools_addon/files/10307456/skeleton.zip)

**Comment by Candoran2** [comment]
Should be fixed, as I was able to import the animation without errors and play it. It also revealed an issue with the autogenerated struct functions in the cobra-tools codegen code, so if you want to test it for yourself you'll need to update that one in addition to the standard new-pyffi and addon code.

**Comment by Allofich** [comment]
Hmm, it did not work for me. I got a new error.

```
Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\operators\kf_import_op.py", line 67, in execute
    return KfImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\kf_import.py", line 79, in execute
    self.transform_anim.import_kf_root(kf_root, b_armature)
  File "****\Blender 3.4\3.4\python\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 209, in import_controller_sequence
    actions.add(self.import_keyframe_controller(kfc, b_armature_obj, b_target, b_action_name))
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 263, in import_keyframe_controller
    self.import_keys(QUAT, b_action, bone_name, times, keys, flags, interp, n_bind_rot_inv, n_bind_trans)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 314, in import_keys
    keys = [key_func(val) for val in keys]
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 314, in <listcomp>
    keys = [key_func(val) for val in keys]
  File "****\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_niftools\modules\nif_import\animation\transform.py", line 56, in as_b_quat
    return mathutils.Quaternion([n_val.w, n_val.x, n_val.y, n_val.z])
AttributeError: 'BaseStruct' object has no attribute 'w'
```

I used:
https://github.com/OpenNaja/cobra-tools/commit/638a4556b1eb1af6592389f75c664156a0937c3d
https://github.com/Candoran2/new-pyffi/commit/4b18387137a4e73386f020fff66d033354ab2186
https://github.com/Candoran2/nifxml/commit/d0ab9271e2c2bf75eacb46082b93e1d304b551e6
https://github.com/Candoran2/blender_nif_plugin/commit/7fd1cdb0fecc9b046599fe1ec5fa4975734707aa

python-3.11.1-amd64.exe
blender-3.4.1-windows-x64.msi

and the `skeleton.nif` and `blockattack.kf` files above.

**Comment by Allofich** [comment]
Actually it is fixed to the point that I can play the animation. Until now every time in my testing that there has been an error in import (rather than a warning) of a file, the import was aborted, but it this case it looks like it does do the import despite the error.

**Comment by Allofich** [comment]
Actually, I will go ahead and close this, since the original issue of failing to import is solved. The `AttributeError: x object has no attribute 'y'` is a common error for many files, and I will consolidate them into https://github.com/niftools/blender_niftools_addon/issues/552.

**Comment by Candoran2** [comment]
> Hmm, it did not work for me. I got a new error.
That was due to the codegen update I mentioned. You'll need the newer version of cobra-tools with the updated StructMetaClass.

**Comment by Allofich** [comment]
Oh, the cobra-tools master branch had been updated when I tested earlier so I thought it included the update you mentioned. I see that it has been updated again, so I'll try the new code.

As I mentioned above, when I did that test the import did complete, despite the error that appeared. I could also play the animation, although I don't know whether the animation was correct or not.

**Comment by Allofich** [comment]
I can confirm that there is no error on import of the .kf file for me anymore. I can also play the animation in Blender.
