### ISSUE TITLE
Python Error when Importing with NIF tools

### ISSUE THREAD

**Issue by GoliathNetworks** [niftools/blender_niftools_addon#570]
I keep getting this error whenever I try to import NIF files. I have tried doing a fresh install and it hasnt seem to fix my issue? Anyone have any ideas?

heres the error.

`Traceback (most recent call last):
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 127, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\nif_import.py", line 75, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\nif_import.py", line 141, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\file_io\nif.py", line 64, in load_nif
    data.read(nif_stream)
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\dependencies\pyffi\formats\nif\__init__.py", line 1297, in read
    self.header.read(stream, data=self)
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\xml\struct_.py", line 373, in read
    attr_value.read(stream, data)
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\xml\array.py", line 303, in read
    elem.read(stream, data)
  File "C:\Users\Not Applicable\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\io_scene_niftools\dependencies\pyffi\object_models\common.py", line 667, in read
    raise ValueError('string too long (0x%08X at 0x%08X)'
ValueError: string too long (0x00060008 at 0x00000069)`

**Comment by Candoran2** [comment]
Is this with all nif files? Are the nif files for a specific game? Could you post an example nif file where this happens?

**Comment by GoliathNetworks** [comment]
> Is this with all nif files? Are the nif files for a specific game? Could you post an example nif file where this happens? Which version of the addon and which version of Blender are you using?

I've tried a couple of different files now and different versions of blender. Originally I was using Steams version of blender (3.3.7) but I tried with the newest version as well (3.5) the same error persisted and I'm using Nifs newest version as well (Blender Niftools Addon - v0.0.14) ive tried reinstalling that a couple of times as well. Heres the file I'm trying 
https://www.nexusmods.com/fallout4/mods/17546

**Comment by Candoran2** [comment]
Fallout 4 is not currently supported. In the mean time, you could try Outfit Studio or some other software to work with Fallout 4 nifs.
