### ISSUE TITLE
I have prompted many errors when importing nif. How can I solve them

### ISSUE THREAD

**Issue by mirkiss** [niftools/blender_niftools_addon#595]
Blender 3.6 
Python 3.11.2
Nif version 20.3.0.9（Gamebryo 2.3）
Blender_niftools_addon version v0.1.1

The error code is as follows：
Python: Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 533, in from_stream
    instance.resolve_references()
  File "D:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 423, in resolve_references
    resolved_ref = self.blocks[block_index]
IndexError: list index out of range

 My nif file  #589 @Candoran2 @amorilia @NickDickinsonWilde @Alphax @hexabits @svip 

[ModNIF.zip](https://github.com/niftools/blender_niftools_addon/files/12384174/ModNIF.zip)

I can open it normally in Nifskope

![20230819060623](https://github.com/niftools/blender_niftools_addon/assets/76403226/7d193b36-f349-4f17-9504-54e6bbc4432c)

**Comment by Candoran2** [comment]
Which game is this from?
