### ISSUE TITLE
"TypeError: bpy_struct: item.attr = val: enum "1" not found in ()" with original Oblivion .NIF file 

### ISSUE THREAD

**Issue by yobowl** [niftools/blender_niftools_addon#597]
# Issue Overview
Attempting to import Oblivion nif file results in error.  Utilizing nif.xml referenced in issue #547 still results in the error.

### Blender Niftools Addon Version Info
NifTools version 0.1.0

### Blender Version Info
Blender Version 3.1.2

### Platform information
Windows 10

## Steps to Reproduce
Import Oblivion nif: architecture\farmhouse\farmhouseconstruction01.nif

## File
[farmhouseconstruction01.zip](https://github.com/niftools/blender_niftools_addon/files/12392891/farmhouseconstruction01.zip)

## Expected Result
Successful import

## Actual Result
Unsuccessful Import without Collision + error.

### Console Output

```
Python: Traceback (most recent call last):
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 240, in import_branch
    b_children.extend(self.import_collision(n_block))
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\nif_import.py", line 184, in import_collision
    return self.bhkhelper.import_bhk_shape(n_node.collision_object.body)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\modules\nif_import\collision\havok.py", line 94, in import_bhk_shape
    return self.process_bhk(bhk_shape)
  File "****\Blender Foundation\Blender 3.1\3.1\python\lib\functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\modules\nif_import\collision\havok.py", line 181, in import_bhk_rigid_body
    self._import_bhk_rigid_body(bhk_shape, collision_objs)
  File "****\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_niftools\modules\nif_import\collision\havok.py", line 216, in _import_bhk_rigid_body
    b_col_obj.nifcollision.collision_layer = str(body_info.havok_filter.layer.value)
TypeError: bpy_struct: item.attr = val: enum "1" not found in ()
```

## Similar Known Issues
(https://github.com/niftools/blender_niftools_addon/issues/547)

**Comment by Candoran2** [comment]
Could you post the actual nif file (easy to do by putting it in a zip file and dragging and dropping when going to edit the issue).

**Comment by yobowl** [comment]
> Could you post the actual nif file? (easy to do by putting it in a zip file and dragging and dropping when going to edit the issue).

Just added it under a file section.

**Comment by Candoran2** [comment]
Thank you. Looks like it has a BS version number that it didn't recognize as being of Oblivion.
