### ISSUE TITLE
Fallout 4 mod import problem

### ISSUE THREAD

**Issue by A-C-E-U** [niftools/blender_niftools_addon#598]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ ] Read the user documentation.
 - [ ] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Issue when importing mesh from fallout 4 mods

### Blender Niftools Addon Version Info
**V 0.1.0**

### Blender Version Info
**3.6.1**

### Platform information
**Windows**

## Context
**When trying to import .nif files from fallout 4 mods I can only improt files that end with GO**

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. 

## Expected Result
**If you import a model without the GO ending it only imports and armature and no mesh**

## Actual Result
**No mesh is improted**

## Possible Fix
**No idea**

## Logs and Files
**Python: Traceback (most recent call last):
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 207, in import_branch
    b_obj = self.armaturehelper.import_armature(n_block)
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 226, in import_armature
    self.store_bind_matrices(n_armature)
  File "C:\Users\ACEEm\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 173, in store_bind_matrices
    self.bind_store[bonenode] = self.get_skin_bind(bonedata.get_transform(), geom, n_armature)
AttributeError: 'BSSkinBoneTrans' object has no attribute 'get_transform'
**

## Additional Information
**[Anything else you feel is relevant]**
[NIF.zip](https://github.com/niftools/blender_niftools_addon/files/12403266/NIF.zip)

**Comment by snipethestatebird** [comment]
I'm having the same problem myself in Blender 3.6
