### ISSUE TITLE
Failing to open Nif File

### ISSUE THREAD

**Issue by jacksw32** [niftools/blender_niftools_addon#610]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X ] Read the user documentation.
 - [X ] Check that the issue hasn't already been reported.
 - [X ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
**[Provide a general introduction to the issue and why it is relevant to this repository]**

### Blender Niftools Addon Version Info
blender_niftools_addon-v0.1.0-2023-06-20-43341a10

### Blender Version Info
Blender 3.6

### Platform information
Windows 10

## Context
When opening a Nif file I have I get the following error:

Python: Traceback (most recent call last):
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 531, in from_stream
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\__init__.py", line 299, in read_blocks
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 403, in from_stream
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 204, in read_fields
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 107, in from_stream
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 64, in read
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 79, in fill
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 79, in <listcomp>
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\array.py", line 64, in <lambda>
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 403, in from_stream
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\base_struct.py", line 204, in read_fields
  File "C:\Users\redcr\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\generated\formats\nif\basic.py", line 53, in from_stream
struct.error: unpack requires a buffer of 4 bytes

### Nif File
**[Attach input or output files, samples of what the expected output should be and reproducing the issue]**
Here is the file I get the issue with: 
[GUM.zip](https://github.com/niftools/blender_niftools_addon/files/12777615/GUM.zip)

**Comment by Candoran2** [comment]
Which game is this for?

**Comment by jacksw32** [comment]
> Which game is this for?

It's not really a game, it is some files from Vizerra they had made some maps and stuff in the Gamebryo engine, here is the link to their archived stuff. http://win98.altervista.org/vizerracom/installers/

**Comment by jacksw32** [comment]
> Which game is this for?

If this is important: 
Free SW to read/convert 3d models:
Models are .NIF files for Gambryo engine. Some are version 20.5.0.0, some are 20.6.0.0;

**Comment by 0010110000** [comment]
I am having the same issue.  Did you find a solution?

**Comment by jacksw32** [comment]
> I am having the same issue. Did you find a solution?

Hexabits Nifskope solves this, he gave me a solution to it.
https://github.com/hexabits/nifskope/issues/64

https://github.com/hexabits/nifskope
