### ISSUE TITLE
Can't enable installed latest version of niftools [0.1.0]

### ISSUE THREAD

**Issue by fronczek7f** [niftools/blender_niftools_addon#613]
Hello, i trying enable new installed version of niftools and i got this error
![error](https://github.com/niftools/blender_niftools_addon/assets/17440369/ee59d3c9-3bce-4814-af26-4ebac11adb28)

3.2 blender
0.1.0 niftools latest release
Windows 10

**Comment by Candoran2** [comment]
After you removed the old version, did you close and reopen Blener?

**Comment by tjFreerey** [comment]
I have also received errors with trying to install the latest version of niftools on Blender 3.2.2, 2.93, and 3.6.4. I did close and reopen Blender with every different version used, but it returns the same addon_utils.py error that fronczek7f is getting.

```
Traceback (most recent call last):
  File "/home/scott/Downloads/blender-3.2.2-linux-x64/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/home/scott/.config/blender/3.2/scripts/addons/io_scene_niftools\__init__.py", line 41, in <module>
    from io_scene_niftools import addon_updater_ops
ModuleNotFoundError: No module named 'io_scene_niftools'
```

Every module is referred to as a "fake module" when running Blender from the terminal. I can confirm this is not a result of older versions of Blender getting in the way of this addon, as I did not have previous versions of Blender installed. This is not acceptable.

**Comment by tjFreerey** [comment]
Thank you @Candoran2 for pointing that out. I will look into that thread.

**Comment by Candoran2** [comment]
Did the new release fix your issue?

**Comment by 2kdragons** [comment]
I was having the same problem and the updated version did not fix it. I got this error message now.

![Screenshot error8](https://github.com/niftools/blender_niftools_addon/assets/149844895/da7e12f2-8676-4e8a-91d2-2621686b5247)


Niftools uses the most recent update of blender, right?

**Comment by Candoran2** [comment]
> Niftools uses the most recent update of blender, right?

Yes, so not 2.78 like in your picture. The current release should be compatible with 2.8 or above.
