### ISSUE TITLE
Add support for Blender 4.0

### ISSUE THREAD

**Issue by Candoran2** [niftools/blender_niftools_addon#621]
The update to Blender 4.0 seems to have cause some errors (see #620 for an example). This issue is to serve as a list of (potential) necessary changes for updating for Blender 4.0 and as a place for discussion in the chosen approach.

### Breaking changes to 4.0
- Face maps were removed in favour of custom face attributes. We use face maps to store the partition for Bethesda games like Oblivion, Fallout 3, Skyrim and others.

**Comment by obliviousXoblivion** [comment]
Any way to like re-enable face maps? Or is it possible to download an old version of blender and the niftools addon to export face maps? 

Just trying to make mods for Oblivion but when I attempt to export the file I am greeted with this message

Python: Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_export.py", line 135, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 104, in export_root_node
    self.export_node(b_obj, None, n_node_type=b_obj.niftools.nodetype)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 216, in export_node
    self.export_node(b_child, node)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 169, in export_node
    mesh = self.mesh_helper.export_tri_shapes(b_obj, n_parent, self.n_root, b_obj.name)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 107, in export_tri_shapes
    polygon_parts = self.get_polygon_parts(b_obj, eval_mesh)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 742, in get_polygon_parts
    face_map = b_obj.face_maps.get(bodypartgroupname)
AttributeError: 'Object' object has no attribute 'face_maps'

**Comment by Candoran2** [comment]
You can still use the current addon with any version of Blender 2.8-3.6

**Comment by BlinkerHigh** [comment]
Are you planning to update your addon for Blender 4+?
