### ISSUE TITLE
Error importing .nif

### ISSUE THREAD

**Issue by Maxandkon** [niftools/blender_niftools_addon#627]
@niftools/blender-niftools-addon-reviewer -

# Issue Overview
When I try to import some .nif files from Morrowind, some of them load perfectly, but some of them have a problem, either they give an error and nothing appear, or only the skeleton of the animation appears

### Blender Niftools Addon Version Info
0.1.1

### Blender Version Info
4.0.2

### Platform information
Windows 10

## Context
I do 3D fan animation, and most of the models I'm interested in don't work. Judging by local my language Morrowind forums, I'm not the only one with this problem

## Steps to Reproduce
**[Ordered list of the steps required for recreating the issue, including settings]**
 #. Import > .nif > choose file

## Expected Result
Loading the model

## Actual Result
Nothing, or only the skeleton of the animation appears

## Possible Fix
¿

## Screenshot
Case when nothing happend
![image](https://github.com/niftools/blender_niftools_addon/assets/36767477/d028a2dd-549b-4371-a74b-6cebebc2b70a)
Case where only the skeleton of the animation appears
![image](https://github.com/niftools/blender_niftools_addon/assets/36767477/aae299dc-634f-4ffb-9c10-996562e90878)

### Info Bar Output
![image](https://github.com/niftools/blender_niftools_addon/assets/36767477/bad97e9f-442e-40c3-ab06-6d27f2cef4ea)
¿

### Console Output
```
Traceback (most recent call last):
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 207, in import_branch
    b_obj = self.armaturehelper.import_armature(n_block)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 225, in import_armature
    self.store_bind_matrices(n_armature)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 162, in store_bind_matrices
    np_normals = np_normals @ np_diff33
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?)
```
```
Traceback (most recent call last):
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 234, in import_branch
    b_child = self.import_branch(n_child, b_armature=b_armature)
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\nif_import.py", line 241, in import_branch
    b_children.extend(self.boundhelper.import_bounding_box(n_block))
  File "C:\Users\Maxandkon\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_niftools\modules\nif_import\collision\bound.py", line 82, in import_bounding_box
    n_b_trans = n_bbox.translation
AttributeError: 'BoxBV' object has no attribute 'translation'
```

### Blend File
-

### Nif File
[Google Drive](https://drive.google.com/drive/folders/10R25trXZFruNo6xYVGYMyp_oyK405Rt9?usp=sharing)
ashslave — example of fully working one
ashghoul — only appear animation skelet
ashvampire — nothing appear

If I must to provide additional files as part of the models/textures. or more error one .nif, please tell

## Similar Known Issues
¿

## Additional Information
As I said, it's quite strange, from the point of view that all these .nif-s are from the same game and even lie in the same folder, but many of them give similar errors, which is why some of them cannot be imported or it will not work correct

Thank you for your time! And for possible response!

**Comment by ChrisNonyminus** [comment]
I'm having this exact issue on Blender 3.6 as well. Can confirm it happens with Morrowinds "base_anim" nifs. (1st person ones load fine)

**Comment by ChrisNonyminus** [comment]
For base_anim, the problem line seems to be "np_normals = np_normals @ np_diff33". If I comment this out, the skeleton loads.

**Comment by PaperDrake148** [comment]
same issue, some models load fine, some throw errors or load only partially. Sunder, Keening and most other unique weapons throw errors about mesh smoothing, but Trueflame loads fine. Tested on Blender 4.4
