### ISSUE TITLE
Error exporting Skyrim SE nif

### ISSUE THREAD

**Issue by ThePagi** [niftools/blender_niftools_addon#628]
# Issue Overview
The following error appears when trying to export a nif file that was previously imported without any modifications.

<details>
Python: Traceback (most recent call last):
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 240, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\base\basic.py", line 86, in validate_instance
    assert (instance == cls.from_value(instance))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 240, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 242, in validate_instance
    raise ValueError(f"Validation failed on {cls_name}.{f_name}")
ValueError: Validation failed on ByteColor4.g

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 240, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\array.py", line 228, in validate_instance
    f_type.validate_instance(cls.get_field(instance, f_name), context, *f_arguments)
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 242, in validate_instance
    raise ValueError(f"Validation failed on {cls_name}.{f_name}")
ValueError: Validation failed on BSVertexDataSSE.vertex_colors

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 148, in execute
    return NifExport(self, context).execute()
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_export.py", line 271, in execute
    data.validate()
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 641, in validate
    type(block).validate_instance(block, self, arg=0, template=None)
  File "C:\Users\exist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\base_struct.py", line 242, in validate_instance
    raise ValueError(f"Validation failed on {cls_name}.{f_name}")
ValueError: Validation failed on BSTriShape.vertex_data

</details>

### Blender Niftools Addon Version Info
0.1.1 (latest in releases)

### Blender Version Info
3.6.5
Tried also with Blender 4.0 - that also had an error while importing

### Platform information
Windows laptop, old intel i5, nvidia 1050ti

## Steps to Reproduce
Import nif file, attempt to export again

### Nif File
Cannot share the files, but it's vanilla Skyrim models, for example meshes\clutter\table01.nif

**Comment by Candoran2** [comment]
This seems to be the same issue faced in #617 (not the initial one but the one that's fixed by RGBA attribute removal).

**Comment by ThePagi** [comment]
Can confirm that removing RGBA color attribute (vertex colors) fixes the export.

**Comment by Orfey1** [comment]
I have the same problem but my file has no RGBA color attribute or anything else inside Vertex Colors. What do I do?
