### ISSUE TITLE
Unable to export Skyrim SE .nif in Blender 3.6

### ISSUE THREAD

**Issue by volkolakgf** [niftools/blender_niftools_addon#631]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [X] Read the user documentation.
 - [X] Check that the issue hasn't already been reported.
 - [X] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [x] Looking for support where the forums, chat or documentation is more appropriate.
 - [x] Goes off topic, loses focus or turns into a discussion.
 - [x] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
When attempting to export a project as an .nif, the export fails and Blender displays this error message:
```
Python: Traceback (most recent call last):
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 148, in execute
    return NifExport(self, context).execute()
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_export.py", line 135, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 104, in export_root_node
    self.export_node(b_obj, None, n_node_type=b_obj.niftools.nodetype)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 216, in export_node
    self.export_node(b_child, node)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 169, in export_node
    mesh = self.mesh_helper.export_tri_shapes(b_obj, n_parent, self.n_root, b_obj.name)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 312, in export_tri_shapes
    n_geom.add_bone(n_node, vert_weights)
AttributeError: 'BSTriShape' object has no attribute 'add_bone'
```

### Blender Niftools Addon Version Info
0.1.1 (latest release)

### Blender Version Info
Version 3.6.8.0. Attempted in 4.0 as well, but the .nif would not even import correctly let alone export.

### Platform information
Microsoft Windows 10 Home

## Context
Imported an .nif I downloaded from a Skyrim SE Nexus mod. Attempted to import into Blender 4.0 with the latest addon release, mesh would not import correctly. Switched to Blender 3.6.8.0 after Googling issue, this time .nif imported correctly. Made minor adjustments to the mesh and attempted export, but the export failed and I received the aforementioned errors. Attempted again, this time importing the .nif and immediately attempting an export again without modification, and the same error occurred.

## Steps to Reproduce
1. Import .nif
2. Attempt to export .nif

## Expected Result
A successful export.

## Actual Result
Export fails and Blender shows above error.

## Possible Fix
Really not sure. I attempted to Google for how to resolve this error, and the closest thing I could find was [this issue](https://github.com/niftools/blender_niftools_addon/issues/628), though as far as I can tell it is not the same issue as that fix did not work for me.

## Screenshot
![SWwYdYWtWB](https://github.com/niftools/blender_niftools_addon/assets/144088792/16756f9b-3723-4830-935b-92803171635a)

### Info Bar Output
```
Python: Traceback (most recent call last):
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_export_op.py", line 148, in execute
    return NifExport(self, context).execute()
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_export.py", line 135, in execute
    root_block = self.objecthelper.export_root_node(self.root_objects, filebase)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 104, in export_root_node
    self.export_node(b_obj, None, n_node_type=b_obj.niftools.nodetype)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 216, in export_node
    self.export_node(b_child, node)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\object\__init__.py", line 169, in export_node
    mesh = self.mesh_helper.export_tri_shapes(b_obj, n_parent, self.n_root, b_obj.name)
  File "C:\Users\dayn\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\modules\nif_export\geometry\mesh\__init__.py", line 312, in export_tri_shapes
    n_geom.add_bone(n_node, vert_weights)
AttributeError: 'BSTriShape' object has no attribute 'add_bone'
```

### Console Output
**[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]**
I genuinely tried for like an hour to do this, but couldn't figure it out. Once I launched Blender via the command prompt, I could no longer type in the console. Not sure why, couldn't find a fix.

### Blend File
https://drive.google.com/file/d/1pZmtvKH9JBWTFc5OreqmhDLJ-7F-WF6S/view?usp=sharing

### Nif File
https://drive.google.com/file/d/1w6OVl58Nkzr7ibteJk_0NSIif5BTxN_F/view?usp=sharing

## Similar Known Issues
https://github.com/niftools/blender_niftools_addon/issues/628) ?

**Comment by arcusmaximus** [comment]
My workaround was to simply export for Skyrim LE instead (you can select the target game in the "Scene" tab of Blender's Properties editor -> "Niftools Scene Panel"). The outfit immediately worked in SE - didn't need to run the .nif through a mesh upgrader.
