### ISSUE TITLE
Digimon - DMO 

### ISSUE THREAD

**Issue by zeak6464** [niftools/blender_niftools_addon#637]
### Blender Niftools Addon Version Info
-Newest Version as of 5/9/2024

### Blender Version Info
2.82

### Platform information
Windows 10

### Console Output
`
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.1.1(running on Blender 2.82 (sub 7), Nif xml version 0.10.0.0)
niftools:INFO:Importing C:\MoveInteractive\Digimon Masters Online(MoveInteractive)\Data\data\digimon\diarbbitmon\diarbbitmon.nif
niftools:INFO:NIF file version: 14030009
niftools:INFO:Reading .nif file
niftools:WARNING:Game set to 'Games.BULLY_SE', but multiple games qualified
niftools:INFO:Importing data
niftools:INFO:Animation estimated at 20 frames per second.
niftools:INFO:Scale Correction set to 0.10000000149011612
pyffi.toaster:INFO:--- fix_scale ---
pyffi.toaster:INFO:  scaling by factor 0.100000
pyffi.toaster:INFO:  ~~~ NiNode [Scene Root] ~~~
pyffi.toaster:INFO:    ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiZBufferProperty [] ~~~
pyffi.toaster:INFO:    ~~~ NiCollisionData [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon_wepon02] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Material #60] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPersistentSrcTextureRendererData [] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Material #59] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPersistentSrcTextureRendererData [] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon_wepon01] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon_cloak] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon_wepon003] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon_wepon004] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [Editable Poly] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Dummy011] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiMultiTargetTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:      ~~~ NiNode [Dummy011 NonAccum] ~~~
pyffi.toaster:INFO:        ~~~ NiNode [Bip001] ~~~
pyffi.toaster:INFO:          ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:          ~~~ NiNode [Bip001 Footsteps] ~~~
pyffi.toaster:INFO:          ~~~ NiNode [Bip001 Pelvis] ~~~
pyffi.toaster:INFO:            ~~~ NiNode [Bip001 Spine] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Bip001 Spine1] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bip001 Neck] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bip001 L Clavicle] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 L UpperArm] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bip001 L Forearm] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bip001 L Hand] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 L Finger0] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 L Finger01] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 L Finger02] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 L Finger1] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 L Finger11] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 L Finger12] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 L Finger2] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 L Finger21] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 L Finger22] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 L Finger3] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 L Finger31] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 L Finger32] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 L Finger4] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 L Finger41] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 L Finger42] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Dummy006] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bone002] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bone004] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Dummy002] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 Xtra02] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bip001 Xtra0202] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bip001 Xtra0203] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 Xtra0204] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 Xtra0205] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 Xtra03] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 Xtra0302] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 Xtra0303] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bone008] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bip001 R Clavicle] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 R UpperArm] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bip001 R Forearm] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bip001 R Hand] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 R Finger0] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 R Finger01] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 R Finger02] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 R Finger1] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 R Finger11] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 R Finger12] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 R Finger2] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 R Finger21] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 R Finger22] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 R Finger3] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 R Finger31] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 R Finger32] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Bip001 R Finger4] ~~~
pyffi.toaster:INFO:                            ~~~ NiNode [Bip001 R Finger41] ~~~
pyffi.toaster:INFO:                              ~~~ NiNode [Bip001 R Finger42] ~~~
pyffi.toaster:INFO:                          ~~~ NiNode [Dummy008] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bone001] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [ride] ~~~
pyffi.toaster:INFO:                          ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bone003] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Dummy001] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bip001 Head] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 Ponytail1] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bip001 Ponytail11] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bip001 Ponytail12] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 Ponytail2] ~~~
pyffi.toaster:INFO:                      ~~~ NiNode [Bip001 Ponytail21] ~~~
pyffi.toaster:INFO:                        ~~~ NiNode [Bip001 Ponytail22] ~~~
pyffi.toaster:INFO:                  ~~~ NiTriStrips [Biped Object] ~~~
pyffi.toaster:INFO:                    ~~~ NiMaterialProperty [] ~~~
pyffi.toaster:INFO:                    ~~~ NiTriStripsData [] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bone007] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Bip001 L Thigh] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bip001 L Calf] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bip001 L Foot] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 L Toe0] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bone006] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Dummy004] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bone010] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Bip001 R Thigh] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bip001 R Calf] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bip001 R Foot] ~~~
pyffi.toaster:INFO:                    ~~~ NiNode [Bip001 R Toe0] ~~~
pyffi.toaster:INFO:                  ~~~ NiNode [Bone005] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Dummy003] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Bone009] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Bip001 Tail] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Dummy010] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Dummy005] ~~~
pyffi.toaster:INFO:              ~~~ NiNode [Dummy009] ~~~
pyffi.toaster:INFO:                ~~~ NiNode [Dummy007] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [diarbbitmon Folish] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiTransformController [] ~~~
pyffi.toaster:INFO:        ~~~ NiTransformInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiTransformData [] ~~~
pyffi.toaster:INFO:      ~~~ NiZBufferProperty [] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShape [PolyMesh] ~~~
pyffi.toaster:INFO:        ~~~ NiStencilProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Polish] ~~~
pyffi.toaster:INFO:        ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiAlphaProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiTextureTransformController [] ~~~
pyffi.toaster:INFO:            ~~~ NiFloatInterpolator [] ~~~
pyffi.toaster:INFO:              ~~~ NiFloatData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPixelData [] ~~~
pyffi.toaster:INFO:        ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:          ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Aura Particle-Emitter] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiParticleSystem [Aura Particle] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysEmitterCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysUpdateCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiFloatInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiBoolInterpolator [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Aura] ~~~
pyffi.toaster:INFO:        ~~~ NiVertexColorProperty [] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPixelData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysAgeDeathModifier [NiPSysAgeDeath:2] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysSpawnModifier [NiPSysSpawnModifier:1] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysMeshEmitter [NiPSysMeshEmitter:0] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysGrowFadeModifier [NiPSysGrowFadeModifier:3] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysColorModifier [NiPSysColorModifier:4] ~~~
pyffi.toaster:INFO:          ~~~ NiColorData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysRotationModifier [NiPSysRotationModifier:5] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysPositionModifier [NiPSysPositionModifier:6] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysBoundUpdateModifier [NiPSysBoundUpdateModifier:7] ~~~
pyffi.toaster:INFO:    ~~~ NiTriShape [Sphere] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [NiStringED003] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [NiStringED001] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [NiStringED002] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [NiStringED000] ~~~
pyffi.toaster:INFO:      ~~~ NiMaterialProperty [OBJ] ~~~
pyffi.toaster:INFO:      ~~~ NiTriShapeData [] ~~~
pyffi.toaster:INFO:      ~~~ NiSkinInstance [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinData [] ~~~
pyffi.toaster:INFO:        ~~~ NiSkinPartition [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Aura Glow Particle-Emitter] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiParticleSystem [Aura Glow Particle] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysEmitterCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysUpdateCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiFloatInterpolator [] ~~~
pyffi.toaster:INFO:          ~~~ NiBoolInterpolator [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Aura Glow] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPixelData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysAgeDeathModifier [NiPSysAgeDeath:2] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysSpawnModifier [NiPSysSpawnModifier:1] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysMeshEmitter [NiPSysMeshEmitter:0] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysGrowFadeModifier [NiPSysGrowFadeModifier:3] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysColorModifier [NiPSysColorModifier:4] ~~~
pyffi.toaster:INFO:          ~~~ NiColorData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysRotationModifier [NiPSysRotationModifier:5] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysPositionModifier [NiPSysPositionModifier:6] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysBoundUpdateModifier [NiPSysBoundUpdateModifier:7] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Twinkle Particle_01-Emitter] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiParticleSystem [Twinkle Particle_01] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:            ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:              ~~~ NiPSysEmitterCtlr [] ~~~
pyffi.toaster:INFO:                ~~~ NiPSysUpdateCtlr [] ~~~
pyffi.toaster:INFO:                ~~~ NiFloatInterpolator [] ~~~
pyffi.toaster:INFO:                ~~~ NiBoolInterpolator [] ~~~
pyffi.toaster:INFO:                  ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:              ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:                ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:              ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:          ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Twinkle_01] ~~~
pyffi.toaster:INFO:        ~~~ NiTexturingProperty [] ~~~
pyffi.toaster:INFO:          ~~~ NiSourceTexture [] ~~~
pyffi.toaster:INFO:            ~~~ NiPixelData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysAgeDeathModifier [NiPSysAgeDeath:2] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysSpawnModifier [NiPSysSpawnModifier:1] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysMeshEmitter [NiPSysMeshEmitter:0] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysGrowFadeModifier [NiPSysGrowFadeModifier:3] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysColorModifier [NiPSysColorModifier:4] ~~~
pyffi.toaster:INFO:          ~~~ NiColorData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysRotationModifier [NiPSysRotationModifier:5] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(X-Axis):8] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(Y-Axis):9] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(Z-Axis):10] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysPositionModifier [NiPSysPositionModifier:6] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysBoundUpdateModifier [NiPSysBoundUpdateModifier:7] ~~~
pyffi.toaster:INFO:    ~~~ NiTriStrips [Cylinder001] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiTriStripsData [] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Twinkle Drag] ~~~
pyffi.toaster:INFO:    ~~~ NiNode [Twinkle Particle_02-Emitter] ~~~
pyffi.toaster:INFO:      ~~~ NiStringExtraData [UserPropBuffer] ~~~
pyffi.toaster:INFO:      ~~~ NiParticleSystem [Twinkle Particle_02] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:            ~~~ NiPSysModifierActiveCtlr [] ~~~
pyffi.toaster:INFO:              ~~~ NiPSysEmitterCtlr [] ~~~
pyffi.toaster:INFO:                ~~~ NiPSysUpdateCtlr [] ~~~
pyffi.toaster:INFO:                ~~~ NiFloatInterpolator [] ~~~
pyffi.toaster:INFO:                ~~~ NiBoolInterpolator [] ~~~
pyffi.toaster:INFO:                  ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:              ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:                ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:              ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:          ~~~ NiBoolTimelineInterpolator [] ~~~
pyffi.toaster:INFO:            ~~~ NiBoolData [] ~~~
pyffi.toaster:INFO:        ~~~ NiMaterialProperty [Twinkle_02] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysAgeDeathModifier [NiPSysAgeDeath:2] ~~~
pyffi.toaster:INFO:          ~~~ NiPSysSpawnModifier [NiPSysSpawnModifier:1] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysMeshEmitter [NiPSysMeshEmitter:0] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysGrowFadeModifier [NiPSysGrowFadeModifier:3] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysColorModifier [NiPSysColorModifier:4] ~~~
pyffi.toaster:INFO:          ~~~ NiColorData [] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysRotationModifier [NiPSysRotationModifier:5] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(X-Axis):8] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(Y-Axis):9] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysDragModifier [NiPSysDragModifier(Z-Axis):10] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysPositionModifier [NiPSysPositionModifier:6] ~~~
pyffi.toaster:INFO:        ~~~ NiPSysBoundUpdateModifier [NiPSysBoundUpdateModifier:7] ~~~
niftools:INFO:Importing data for block 'Scene Root'
Traceback (most recent call last):
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\nif_import.py", line 131, in execute
    self.import_root(root)
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\nif_import.py", line 159, in import_root
    b_obj = self.import_branch(root_block)
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\nif_import.py", line 207, in import_branch
    b_obj = self.armaturehelper.import_armature(n_block)
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 225, in import_armature
    self.store_bind_matrices(n_armature)
  File "C:\Users\zeak6\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\io_scene_niftools\modules\nif_import\armature\__init__.py", line 162, in store_bind_matrices
    np_normals = np_normals @ np_diff33
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 0)
`

## Steps to Reproduce
importing Nif file

## Actual Result
Nothing loaded except for "Scene Root"

[Diarbbitmon.zip](https://github.com/niftools/blender_niftools_addon/files/15261903/Diarbbitmon.zip)
![image](https://github.com/niftools/blender_niftools_addon/assets/2738141/2fb25bbf-758a-49e8-b428-18b4326b9dc8)

**Comment by dragonwithin** [comment]
do you ever tryed to import fbx or dae files and make them nif for dmo ?
