### ISSUE TITLE
Cannot Import Starfield NIFs Getting Python Errors

### ISSUE THREAD

**Issue by TheAdminKing** [niftools/blender_niftools_addon#652]
@niftools/blender-niftools-addon-reviewer -

Before creating a new issue, ensure that
 - [ x] Read the user documentation.
 - [ x] Check that the issue hasn't already been reported.
 - [ ] Read through the list of `Helpful resources` links on the right-hand side.
 - [ ] Talk with the developers to ensure its a valid issue

The issue will get closed off immediately as invalid if
 - [ ] Looking for support where the forums, chat or documentation is more appropriate.
 - [ ] Goes off topic, loses focus or turns into a discussion.
 - [ ] Removing parts of the template the issue.

Fill out the template below to the best of your ability, including .blend files, nifs, logs; help us to help you.

# Issue Overview
Cannot Import any NIFs extracted from starfield. Getting Python Errors

### Blender Niftools Addon Version Info
**[0.1.1]**

### Blender Version Info
**[3.6.16]**

### Platform information
[resourcealdumitechunk01.zip](https://github.com/user-attachments/files/17244562/resourcealdumitechunk01.zip)

**[Windows 11 23H2]**

## Context
**[Provide more detailed information to the issue itself and why it is relevant]**

## Steps to Reproduce
**[Extract Starfield BA2s, Open Blender 3.6, Click Import, Find any Starfield nif file extracted from the BA2s and try to load it]**
 #. 

## Expected Result
**[Meshes to Load]**

## Actual Result
**[Python Errors Occur and Nothing Loads]**

## Possible Fix
**[Optional, suggest fixes, improvement or reasons for the bug might have occurred]**

## Screenshot
**[If relevant, include a screenshot]**

## Logs and Files
**[Provide logs file generated during the error as well as the blend and nif files are related to the issue]**

### Info Bar Output
**[Output from the Info View, available at top of Blender viewport, drag to expand]**

### Console Output
**[Writing userprefs: "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend" ok
Info: Preferences saved

addon_utils.disable: io_scene_niftools not disabled
Modules Installed (io_scene_niftools) from 'E:\\Downloads\\blender_niftools_addon-v0.1.1-2023-11-03-0305c8d5.zip' into 'C:\\Users\\StonedGorillaKing\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons'
{'INFO'}: Loading: Blender Niftools Addon: v0.1.1

{'INFO'}: Loading: NifFormat: 0.10.0.0
{'DEBUG'}: Starting registration
{'DEBUG'}: Configuring auto-updater
io_scene_niftools updater verbose is enabled
io_scene_niftools: Wrote out updater JSON settings to file, with the contents:
{'last_check': '', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
{'DEBUG'}: Registering submodules for: io_scene_niftools
{'DEBUG'}: Registering Classes for module: io_scene_niftools.update
{'DEBUG'}: Registered Classes: ['UpdaterPreferences']
{'DEBUG'}: Registering submodules for: io_scene_niftools.properties
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.armature
{'DEBUG'}: Registered Classes: ['BoneProperty', 'ArmatureProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.collision
{'DEBUG'}: Registered Classes: ['CollisionProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.constraint
{'DEBUG'}: Registered Classes: ['ConstraintProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.material
{'DEBUG'}: Registered Classes: ['Material', 'AlphaFlags']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.object
{'DEBUG'}: Registered Classes: ['BsInventoryMarker', 'ExtraData', 'ExtraDataStore', 'ObjectProperty']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.shader
{'DEBUG'}: Registered Classes: ['ShaderProps']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.properties.scene
{'DEBUG'}: Registered Classes: ['Scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.properties.armature', 'io_scene_niftools.properties.collision', 'io_scene_niftools.properties.constraint', 'io_scene_niftools.properties.material', 'io_scene_niftools.properties.object', 'io_scene_niftools.properties.shader', 'io_scene_niftools.properties.scene']
{'DEBUG'}: Registering submodules for: io_scene_niftools.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.object
{'DEBUG'}: Registered Classes: ['BSXExtraDataAdd', 'UPBExtraDataAdd', 'SampleExtraDataAdd', 'NiExtraDataRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.geometry
{'DEBUG'}: Registered Classes: ['BsInvMarkerAdd', 'BsInvMarkerRemove']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_import_op
{'DEBUG'}: Registered Classes: ['NifImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.nif_export_op
{'DEBUG'}: Registered Classes: ['NifExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_import_op
{'DEBUG'}: Registered Classes: ['KfImportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.kf_export_op
{'DEBUG'}: Registered Classes: ['KfExportOperator']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.operators.egm_import_op
{'DEBUG'}: Registered Classes: ['EgmImportOperator']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.operators.object', 'io_scene_niftools.operators.geometry', 'io_scene_niftools.operators.nif_import_op', 'io_scene_niftools.operators.nif_export_op', 'io_scene_niftools.operators.kf_import_op', 'io_scene_niftools.operators.kf_export_op', 'io_scene_niftools.operators.egm_import_op']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.armature
{'DEBUG'}: Registered Classes: ['BonePanel', 'ArmaturePanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.collision
{'DEBUG'}: Registered Classes: ['CollisionBoundsPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.material
{'DEBUG'}: Registered Classes: ['MaterialColorPanel', 'MaterialFlagPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.object
{'DEBUG'}: Registered Classes: ['ObjectExtraDataList', 'ObjectExtraDataType', 'ObjectExtraData', 'ObjectPanel', 'ObjectBSInvMarkerPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators
{'DEBUG'}: Registered Classes: ['OperatorCommonDevPanel']
{'DEBUG'}: Registering submodules for: io_scene_niftools.ui.operators
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_import
{'DEBUG'}: Registered Classes: ['OperatorImportIncludePanel', 'OperatorImportTransformPanel', 'OperatorImportGeometryPanel', 'OperatorImportTexturePanel', 'OperatorImportArmaturePanel', 'OperatorImportOverrideArmatureOrientationPanel', 'OperatorImportAnimationPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.operators.nif_export
{'DEBUG'}: Registered Classes: ['OperatorExportTransformPanel', 'OperatorExportArmaturePanel', 'OperatorExportAnimationPanel', 'OperatorExportOptimisePanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.operators.nif_import', 'io_scene_niftools.ui.operators.nif_export']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.shader
{'DEBUG'}: Registered Classes: ['ShaderPanel']
{'DEBUG'}: Registering Classes for module: io_scene_niftools.ui.scene
{'DEBUG'}: Registered Classes: ['ScenePanel', 'SceneVersionInfoPanel']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.ui.armature', 'io_scene_niftools.ui.collision', 'io_scene_niftools.ui.material', 'io_scene_niftools.ui.object', 'io_scene_niftools.ui.operators', 'io_scene_niftools.ui.shader', 'io_scene_niftools.ui.scene']
{'DEBUG'}: Registered the following submodules: ['io_scene_niftools.update', 'io_scene_niftools.properties', 'io_scene_niftools.operators', 'io_scene_niftools.ui']
Writing userprefs: "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend" ok
Info: Preferences saved

Info: Deleted 1 object(s)

niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.1.1(running on Blender 3.6.16, Nif xml version 0.10.0.0)
niftools:INFO:Importing M:\Starfield BA2 Extracted\meshes\landscape\resources\ore\resourceindicitechunk01.nif
niftools:INFO:NIF file version: 14020007
niftools:INFO:Reading .nif file
Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 297, in read_blocks
    block_class = niobject_map[block_type]
KeyError: 'BSGeometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 553, in from_stream
    instance.read_blocks(stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 302, in read_blocks
    raise ValueError(error_msg)
ValueError: Unknown block type BSGeometry on stream position 11146 with index 5.
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.1.1(running on Blender 3.6.16, Nif xml version 0.10.0.0)
niftools:INFO:Importing M:\Starfield BA2 Extracted\meshes\landscape\resources\ore\resourcealdumitechunk01.nif
niftools:INFO:NIF file version: 14020007
niftools:INFO:Reading .nif file
Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 297, in read_blocks
    block_class = niobject_map[block_type]
KeyError: 'BSGeometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 553, in from_stream
    instance.read_blocks(stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 302, in read_blocks
    raise ValueError(error_msg)
ValueError: Unknown block type BSGeometry on stream position 12634 with index 5.
niftools:INFO:Dev: Sys variable not set
niftools:INFO:Executing - Niftools : Blender Niftools Addon v0.1.1(running on Blender 3.6.16, Nif xml version 0.10.0.0)
niftools:INFO:Importing M:\Starfield BA2 Extracted\meshes\landscape\resources\ore\resourcealdumitechunk01.nif
niftools:INFO:NIF file version: 14020007
niftools:INFO:Reading .nif file
Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 297, in read_blocks
    block_class = niobject_map[block_type]
KeyError: 'BSGeometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 553, in from_stream
    instance.read_blocks(stream)
  File "C:\Users\StonedGorillaKing\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 302, in read_blocks
    raise ValueError(error_msg)
ValueError: Unknown block type BSGeometry on stream position 12634 with index 5.]**

### Blend File
**[Attach the blend file if the issue is reproducible]**

### Nif File
**[attached]**

## Similar Known Issues
**[Reference any known issues - https://github.com/niftools/blender_niftools_addon/issues]**

## Additional Information
**[Anything else you feel is relevant]**

**Comment by Maverick1000** [comment]
I am also having issue with your addon.  I have try blender 2.91 - 4.4 version and have not issue with adding the Add-on, but when trying to import a .nif file I get the follow:

Python: Traceback (most recent call last):
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 297, in read_blocks
    block_class = niobject_map[block_type]
KeyError: 'BSGeometry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\operators\nif_import_op.py", line 134, in execute
    return NifImport(self, context).execute()
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 74, in execute
    self.load_files()  # needs to be first to provide version info.
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\nif_import.py", line 140, in load_files
    NifData.init(NifFile.load_nif(NifOp.props.filepath))
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\file_io\nif.py", line 65, in load_nif
    data = NifFormat.NifFile.from_stream(nif_stream)
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 553, in from_stream
    instance.read_blocks(stream)
  File "C:\Users\pwalker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\io_scene_niftools\dependencies\nifgen\formats\nif\__init__.py", line 302, in read_blocks
    raise ValueError(error_msg)
ValueError: Unknown block type BSGeometry on stream position 13040 with index 4.

location: <unknown location>:-1
